### ISSUE TITLE
Invalid API key. Please see https... 

### ISSUE THREAD

**Issue by jacobgonzales20** [Akylas/oss-weather#102]
Invalid API key. Please see https...

- Text is cut off on the screen

Device: 
iPhone 14 Pro
iOS 17.3.1

![signal-2024-02-26-100533_002](https://github.com/Akylas/oss-weather/assets/122128828/4f77586c-0185-4cc2-98d5-517e50e557e0)

**Comment by farfromrefug** [comment]
@jacobgonzales20 thanks for the report. What we you doing when you got that?

**Comment by farfromrefug** [comment]
@jacobgonzales20 ok the issue with the "invalid" key might be that now OWM restrain the use of free api key from onecall API 2.5 (which i use). Though i did not find definitive answer on their website

**Comment by jacobgonzales20** [comment]
> @jacobgonzales20 ok the issue with the "invalid" key might be that now OWM restrain the use of free api key from onecall API 2.5 (which i use). Though i did not find definitive answer on their website

understandable, none the less. This app has a lot of potential, thank you for making it. Looking forward to improved UI design.
