### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by rlucassen2** [Akylas/oss-weather#105]
The app crashes on start. This has begun a week ago (or two weeks) and most of the time insisting to start the app made it work again. Yesterday I tried to use another data provider in 1.9.1.95 and now it crashes after 1 second. Even the latest version 1.9.2.96 has the same problem. I run a:

adb logcat -d | grep -i akylas

[akylas.txt](https://github.com/Akylas/oss-weather/files/14411762/akylas.txt)

I'm not a programmer, so if I can do some more tests I'm at your service. LineageOS 20 on a OnePlus A5001

HTH,

**Comment by farfromrefug** [comment]
@rlucassen2 really sorry to hear that. willake you a test build tomorrow so that I can get a bug report

**Comment by rlucassen2** [comment]
Ok, no prob. I'm quite busy tomorrow but I will try to find some time.

R.

**Comment by farfromrefug** [comment]
@rlucassen2 here is the test build https://github.com/Akylas/oss-weather/releases/tag/android%2Fsentry
Take your time to test. no rush!

**Comment by rlucassen2** [comment]
Nope, immediate crash:

[akylas.txt](https://github.com/Akylas/oss-weather/files/14416709/akylas.txt)

Do you need the whole logcat or is the grepped one ok?

**Comment by farfromrefug** [comment]
@rlucassen2 so it crashes with the test build? Did you try to restart the app just after. It should send me a bug report (if the crash does not happen too soon)

**Comment by rlucassen2** [comment]
Yes, it's an A5010 indeed. When I start the app I see a black screen with the sun for approx 1 second. Here is the full log of minute 09:50 CET:

[akylas.txt](https://github.com/Akylas/oss-weather/files/14416833/akylas.txt)

R.

**Comment by farfromrefug** [comment]
@rlucassen2 ok i got your log and i know what the error is. Just do not know where. Making a new test build for you. Thanks a lot for testing this!

**Comment by rlucassen2** [comment]
I have another OnePlus A5000, LineageOS 20. OSS Weather 1.8.11.93 (IzzyOnDroid). This one works. I updated to 1.9.2.96 and this one works as well. I rebooted the A5010 to be sure I have a clean system, but it crashes immediately. I removed the app and reinstalled the version 1.9.2.96 and now it works. Must be some config issue I fear. I changed the data source to Meteo France and Opoenweather but it still works.

**Comment by rlucassen2** [comment]
I altered a few times the data sources and it keeps working. Maybe the new version is ok but is not able to work with a corrupted config?

**Comment by farfromrefug** [comment]
@rlucassen2 ok glad it works again. I think you were in a strange state. If it happens again with the next build i ll get a report.
as for comparing data sources yes it is somehting i want to do (we have an issue about this). Though it is a lot of work and will require a new design. Will mostly do it as a graph view, not as you see it in the app today.

**Comment by rlucassen2** [comment]
Ok,thnx, I will get back to work now :-(

**Comment by farfromrefug** [comment]
@rlucassen2 will close this for now. hope it won't happen again
