### ISSUE TITLE
apikey

### ISSUE THREAD

**Issue by frankrudis** [Akylas/oss-weather#107]
hi there,my issue: doesn't save the apikey.thanks

**Comment by farfromrefug** [comment]
@frankrudis are you on iOS/ Android?

**Comment by frankrudis** [comment]
hi, crdroid 7.16   android 11,thanks--Sent from my Android phone with GMX Mail.On 27/02/2024, 14:13 farfromrefuge ***@***.***> wrote:

   
  @frankrudis are you on iOS/ Android?

**Comment by jacobgonzales20** [comment]
iOS doesn't save the api key either 

iOS v: 17.3.1

**Comment by farfromrefug** [comment]
@jacobgonzales20 @frankrudis i need a little bit more details.I tested here and the OWM api key is correctly saved and used upon app restart.
You are talking about settings the api Key from the settings or from the bottom sheet which appears on app start while using OWM ?

**Comment by frankrudis** [comment]
hi there,both from bottom sheet and menue....when i close the app and restart key is gone...i' m talking about the openweathermap api...thanks--Sent from my Android phone with GMX Mail.On 29/02/2024, 10:55 farfromrefuge ***@***.***> wrote:

   
  @jacobgonzales20 @frankrudis i need a little bit more details.I tested here and the OWM api key is correctly saved and used upon app restart. You are talking about settings the api Key from the settings or from the bottom sheet which appears on app start while using OWM ?

**Comment by jacobgonzales20** [comment]
> @jacobgonzales20 @frankrudis i need a little bit more details.I tested here and the OWM api key is correctly saved and used upon app restart. You are talking about settings the api Key from the settings or from the bottom sheet which appears on app start while using OWM ?

When you go into settings and then paste your API key, it doesn't save, or at least it is displayed as saved.

**Comment by farfromrefug** [comment]
@jacobgonzales20 strange I can't reproduce

**Comment by frankrudis** [comment]
never mind,like the app,thanks--Sent from my Android phone with GMX Mail.On 01/03/2024, 08:00 farfromrefuge ***@***.***> wrote:

   
  @jacobgonzales20 strange I can't reproduce
