### ISSUE TITLE
Ability to add filters

### ISSUE THREAD

**Issue by jacobgonzales20** [Akylas/oss-weather#108]
The ability to add filters to show weather data relevant to user preferences

**Comment by jacobgonzales20** [comment]
> @jacobgonzales20 what filters are you talking about?

Toggles/filters to filter out weather data. Let's say someone doesn't want to see wind speed. They could toggle that filter off/on. The same goes with other weather data. This would allow customization, battery savings, and users to de-clutter their weather app to their liking.

**Comment by farfromrefug** [comment]
@jacobgonzales20 could be done. Would not have much impact on battery though.
I might add that in the future but i would say not a prioriity

**Comment by farfromrefug** [comment]
@jacobgonzales20 are you ok to close this one with latest versions?
