### ISSUE TITLE
In App feedback button

### ISSUE THREAD

**Issue by jacobgonzales20** [Akylas/oss-weather#109]
A button to send feedback in the app, there is a budgeting app called cashew that does this really well. 

https://github.com/jameskokoska/Cashew

**Comment by farfromrefug** [comment]
@jacobgonzales20 good idea i ll add that

**Comment by jacobgonzales20** [comment]
> @jacobgonzales20 good idea i ll add that

It would be useful and Cashew has a clean interface for it as well

**Comment by jacobgonzales20** [comment]
has been added
