### ISSUE TITLE
Some Features & Suggestions

### ISSUE THREAD

**Issue by HonestAbe7** [Akylas/oss-weather#11]
Thanks for this app! I currently use Forecastie because I like to see the current temperature in my notifications. What I like about this app is that it shows the days of the week much clearer. Yes, the font is small but no busy.

My suggestion is to have the temperature in the notification bar, a possible widget in the future, and to change the military time to regular standard time for the hours of the current day for an easier read.

**Comment by farfromrefug** [comment]
@HonestAbe7 thanks for the report. I will think about it but honesty might never happen.
One of the main point of this app was to use as less battery/network as possible. Live temperature and such goes against it.
