### ISSUE TITLE
Infinite refreshing icon 

### ISSUE THREAD

**Issue by jacobgonzales20** [Akylas/oss-weather#127]
When you pull down to refresh, the refresh icon will stay displayed. 

![signal-2024-03-08-004830_002](https://github.com/Akylas/oss-weather/assets/122128828/ad1f45ac-144a-42a6-9f9d-e49f50c23ab4)

**Comment by farfromrefug** [comment]
@jacobgonzales20 does it happen all the time?

**Comment by jacobgonzales20** [comment]
> @jacobgonzales20 does it happen all the time?

yes

**Comment by farfromrefug** [comment]
@jacobgonzales20 ok i fixed it. Big update coming!

**Comment by jacobgonzales20** [comment]
Fixed on version 1.10.0
