### ISSUE TITLE
Icons pack breaks the app

### ISSUE THREAD

**Issue by t0xicP0w3r** [Akylas/oss-weather#129]
After the latest update(1.11.0.99), when i start the app, it freezes and crash.
After clearing the data of the app, it started just fine, and before setting up a location i changed the icon pack and it solved the problem
The broken icon pack:⬇️
![Screenshot_20240311_141837_OSS Weather.jpg](https://github.com/Akylas/oss-weather/assets/122619443/969a6d02-614e-47f0-8b2f-c4c5a0cd83da)

**Comment by farfromrefug** [comment]
@t0xicP0w3r really sorry about that. Will try to fix right away!
thanks for reporting

**Comment by farfromrefug** [comment]
@t0xicP0w3r i tried to reproduce the issue:
when i open the app i see a black page with no data. If i pull to refresh the weather did update and the app was working correctly. So i need a bit more details if possible:
* what provider were you using?
* if possible what location?

**Comment by farfromrefug** [comment]
@t0xicP0w3r yes you record your screen using apps on fdroid like https://f-droid.org/packages/com.orpheusdroid.screenrecorder/

**Comment by farfromrefug** [comment]
@t0xicP0w3r awesome i just managed to reproduce it! on it!
Thanks for the great report

**Comment by farfromrefug** [comment]
@t0xicP0w3r the new release is up which should fix this.
