### ISSUE TITLE
Icon pack crashes app

### ISSUE THREAD

**Issue by ghost** [Akylas/oss-weather#131]
Switching the icon pack to line cause the app to crash on every open.

**Comment by farfromrefug** [comment]
@jacobgonzales20 This is iOS right ?

**Comment by jacobgonzales20** [comment]
> @jacobgonzales20 This is iOS right ?

yes iOS 17.3.1

**Comment by jacobgonzales20** [comment]
The issue can be temporarily fixed by reinstalling the app to clear the cache.

**Comment by farfromrefug** [comment]
@jacobgonzales20 thanks i think it was an issue that i now have fixed. There is a new version in review. Hopefully this wont happen again as i am not 100% sure i fixed it :s

**Comment by jacobgonzales20** [comment]
> @jacobgonzales20 thanks i think it was an issue that i now have fixed. There is a new version in review. Hopefully this wont happen again as i am not 100% sure i fixed it :s

This is still an issue

**Comment by farfromrefug** [comment]
@jacobgonzales20 ok i need to reproduce this. May i ask the location you are testing that with? It might be related to the current weather forecast there

**Comment by jacobgonzales20** [comment]
> @jacobgonzales20 ok i need to reproduce this. May i ask the location you are testing that with? It might be related to the current weather forecast there

currently grand rapids michigan

**Comment by farfromrefug** [comment]
@jacobgonzales20 i cant get it to crash :s What provider are you using? your phone is in english?

**Comment by jacobgonzales20** [comment]
> @jacobgonzales20 i cant get it to crash :s What provider are you using? your phone is in english?

Phone in English and app set to english

**Comment by farfromrefug** [comment]
@jacobgonzales20 the bug is fixed and the app is waiting for review!

**Comment by jacobgonzales20** [comment]
fixed

**Comment by jacobgonzales20** [comment]
Issue is apparent again in Build 102; Version 2.3.0

**Comment by jacobgonzales20** [comment]
> Issue is apparent again in Build 102; Version 2.3.0


https://github.com/Akylas/oss-weather/assets/122128828/d1243a24-f1f3-4067-8f38-c63af8494fb8
