### ISSUE TITLE
precipitation data misaligned in hourly chart

### ISSUE THREAD

**Issue by Mrnofish** [Akylas/oss-weather#134]
Congrats on the app, I like it a lot.

Since I've begun using it, however, I noticed there is a misalignment between precipitation data and weather information in the hourly chart.

This can be verified inside the app: if you have sunny weather at noon and rain the following hour, the app will show chance of weather and precipitation amount under sunny weather.

The misalignment is also seen at the end of any precipitation block. (See screenshot)

It can be confirmed with other apps that fetch the same data.

![OSS Weather precipitation misalignment](https://github.com/Akylas/oss-weather/assets/28036193/6b1d5c4c-27c2-4ad9-a751-4931909110d4)

**Comment by farfromrefug** [comment]
@Mrnofish thanks for the kind words.
About the issue what provider are you using?

**Comment by Mrnofish** [comment]
Open meteo. Meteo France dire not seem to provide precipitation data at all and I don't bother with OWM.

**Comment by farfromrefug** [comment]
@Mrnofish oknwillntry to reproduce and fix. BTW météo France does provide it. not sure of the quality outside of France though

**Comment by farfromrefug** [comment]
@Mrnofish should be fixed now

**Comment by Mrnofish** [comment]
@farfromrefug yes, it's been working as expected for at least... a couple versions?

Thanks for the prompt fix and keep up the good work.
