### ISSUE TITLE
Querying OWM API doesn't handle redirection

### ISSUE THREAD

**Issue by snezhniylis** [Akylas/oss-weather#14]
Most of the time I try refreshing my weather feed I get the following error:
![Screenshot_20221027-095617_OSS_Weather_1](https://user-images.githubusercontent.com/85341530/198216768-e39d483c-0251-4e32-bff7-2909d5e1b414.png)

This can be bypassed by using VPN to get another end point.

`curl`-ing both `api.openweathermap.org` and `82.196.7.246` yields the following response:
```
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

My assumed solution is to [properly handle redirection](https://stackoverflow.com/a/62244338).

**Comment by farfromrefug** [comment]
@snezhniylis thanks for the detailed report. are you sure the redirection is not on your side(network)? i have checked and owm api is still on `api.openweathermap.org`
plus android should handle redirection on its own.
The weird thing to me is that you are not seeing it all the time? Are you seeing it on wifi? cellular network?

**Comment by snezhniylis** [comment]
It seems like there are actually 2 issues that I mixed up.

1. `301` redirection happens no matter where the request originated from (Russia, US, Netherlands, ... via a VPN) and always leads to `https://openweathermap.org/api`:

   ```sh
   $ curl -I api.openweathermap.org
   
   HTTP/1.1 301 Moved Permanently
   Server: openresty
   Date: Mon, 31 Oct 2022 10:39:22 GMT
   Content-Type: text/html
   Content-Length: 166
   Connection: keep-alive
   Location: http://openweathermap.org/api
   
   $ curl -I http://openweathermap.org/api
   
   HTTP/1.1 301 Moved Permanently
   Server: openresty/1.9.7.1
   Date: Mon, 31 Oct 2022 10:46:57 GMT
   Content-Type: text/html
   Content-Length: 190
   Connection: keep-alive
   Location: https://openweathermap.org/api
   ```
   So, I don't think it affects anything. As you mentioned, the OS handles this case.

2. Sometimes API requests time out. I could not, for the life of me, find the pattern. Some days it works, some days it doesn't. But, so far, using a VPN reliably solved the issue for me.

   I suspect Roskomnadzor (Russian censorshop agency) messing up somewhere and adding a couple OWM IPs to their blocklist.

   I haven't been able to reproduce this issue for a couple of days. When/If it will pop up again, I'll try digging deeper.

**Comment by snezhniylis** [comment]
It's been a month and I haven't been able to reproduce this issue, so I'm going to close it. If this happens again, I'll make sure to investigate the cause, and, potentially, reopen the issue.
