### ISSUE TITLE
Support for One Call API 3.0

### ISSUE THREAD

**Issue by jacobgonzales20** [Akylas/oss-weather#141]
With support for one call API 2.5 ending on April 15, 2024. Support for one call API 3.0 would be needed to keep the app working with open weather map. 

https://openweathermap.org/api/one-call-api

**Comment by farfromrefug** [comment]
@jacobgonzales20 it should be already possible. You should be able to select it from the providers settings

**Comment by jacobgonzales20** [comment]
> @jacobgonzales20 it should be already possible. You should be able to select it from the providers settings

I found it, though the popup for refresh is quite annoying.

**Comment by farfromrefug** [comment]
@jacobgonzales20 what refresh popup are you talking about?

**Comment by jacobgonzales20** [comment]
> @jacobgonzales20 what refresh popup are you talking about?

![signal-2024-04-02-145632_002](https://github.com/Akylas/oss-weather/assets/122128828/7d4fe77a-3128-4d10-8121-cd60f9018da3)

**Comment by farfromrefug** [comment]
@jacobgonzales20 It comes from OpenWeather. It means your key is not compatible with 3.0
