### ISSUE TITLE
Allow saving meteograms as images

### ISSUE THREAD

**Issue by Atrate** [Akylas/oss-weather#168]
It'd be nice if it would be possible to save the meteograms (and other images from meteoblue) to the device storage.

**Comment by farfromrefug** [comment]
@Atrate Not sure it is a good idea. Already dont really have the actual permission to do what i do acquiring meteoblue images. I would not want to go against license.
Will think about it

**Comment by farfromrefug** [comment]
@Atrate implemented in latest

**Comment by Atrate** [comment]
Looks to be working, thank you!
