### ISSUE TITLE
Meteoblue units don't respect app settings

### ISSUE THREAD

**Issue by Atrate** [Akylas/oss-weather#169]
When using meteoblue with the application set to °C, it still shows temperatures in °F in the meteogram and other images. It'd be nice it it respected the application unit settings.

**Comment by farfromrefug** [comment]
@Atrate not sure i can do anything. Will see. MeteoBlue is already kind of a trick ;)

**Comment by farfromrefug** [comment]
@Atrate metric system is applied in latest version

**Comment by Atrate** [comment]
Looks to be working, thank you!
