### ISSUE TITLE
Norwegian Meteorological Institute source

### ISSUE THREAD

**Issue by julianfairfax** [Akylas/oss-weather#17]
It would be nice if data from the Norwegian Meteorological Institute was available. Their data is open (https://www.met.no/en/free-meteorological-data) and seems to support the whole world. GNOME Weather uses it as its sole provider of weather data. It would be nice to be able to have the same source for GNOME and OSS Weather.

**Comment by farfromrefug** [comment]
@julianfairfax thanks I can look at it

**Comment by farfromrefug** [comment]
@julianfairfax dont have much time no sorry. 
But either someone can contribute or you can wait. 
Yes we need an alternative to own as it is now failing for newly created accounts.
I am not sure what source to use though. Already existing meteo France source should work anywhere. I am also very interested by open meteo.

**Comment by farfromrefug** [comment]
@julianfairfax that must be a bug that i will fix!
I think meteo france data is open as open-meteo seems to be using it. But i am not 100% sure!

**Comment by farfromrefug** [comment]
@julianfairfax thanks for pointing to.the gitlab issue for fdroid. I replied there but to be honest I am still questioning if wether I want my app on f-droid. From an ecological point of view f-droid is really bad.
