### ISSUE TITLE
Daily view written date issue

### ISSUE THREAD

**Issue by 0-5-0** [Akylas/oss-weather#174]
When I click on the new daily view to open the page that shows pollutants/pollen, I tap "Friday" from the main screen, it shows Friday's temperature, wind speed, etc. but the date written in the top right is the previous day (Thursday).

The same is repeatable for all the days in daily list view when I tap them individually to open the daily view. Saturday, it shows Friday, I tap Sunday, it writes Saturday in the top right, etc..

The rest of the measurements look ok so I'm not sure if the date being listed 1 day behind is related to that timezone bug that was there previously in the daily "list" view.

I tapped "Friday" in the daily list view and you can see it's written Thursday:

<img src="https://github.com/Akylas/oss-weather/assets/112411524/ebea9502-9d66-4b2a-852c-30e4bb17c3b5" width=50% height=50%>

**Comment by farfromrefug** [comment]
@0-5-0 thanks. And it does not look good there! everything seems out of place.
What s your system font scale?

**Comment by 0-5-0** [comment]
I'm also wondering if maybe it trimmed a bunch of the "current" day chart (which would have been looking for yesterday's 8PM data) because of the date in the top right? If I click on Sunday it's probably a good example it shows "Saturday" in the top right, then the chart starts at 4:00PM Saturday.

You can kind of see the same thing in the screenshots above where I had opened Saturday, it shows Friday in the top right then the chart starts Friday 8-9PM and goes into Saturday.

It might be the date thing/timezone issue throwing it off.

**Comment by farfromrefug** [comment]
@0-5-0 thanks for the detailed report! (as usual!). I will update a new version which will hopefully fix it

**Comment by 0-5-0** [comment]
The date looks ok now on the latest version, I noticed if I enable "Weather Data -> Show current day in daily list", this is what's causing the first day in the daily list to show up with no chart in the daily view. It also staggers the rest of the charts for all the days.

**Comment by 0-5-0** [comment]
The data in the chart also seems to start on the previous day still. If I open Wednesday from Daily List, it shows Wednesday in Daily View, but the "new" chart starts on Tuesday. This is all with "show current day in daily list" unselected.

I also tried using Grenoble and it looks fine using Grenoble with "show current day" selected or unselected, but Thursday has no chart for some reason.

So it's as if the timezone issue also applies separately to the chart itself. You can try with Toronto Canada to test.

**Comment by farfromrefug** [comment]
@0-5-0 i cant reproduce the wrong date yet. will try more.
Also for thursday not showing chart that s normal. charts are based on hourly data. And we only get a limited number of them in prediction (around 72 hours)

**Comment by 0-5-0** [comment]
Here's an example where I selected Wednesday using Toronto as the location from the Daily View list, you can see the chart starts "Tue" and then finishes "Wed".
<img src="https://github.com/Akylas/oss-weather/assets/112411524/083eae1b-9147-46e7-9d59-d0a12bf36ec4" width=40% height=40%>

The same thing, selecting Wednesday in the Daily View list but with Grenoble as the location, you can see the chart starts "Wed" and ends "Wed".
<img src="https://github.com/Akylas/oss-weather/assets/112411524/37d38274-bb10-456a-91ab-d9e010c39b47" width=40% height=40%>

This is why I think the chart itself also has the timezone issue that the top right date had and that the Daily View list had :sweat_smile:

**Comment by 0-5-0** [comment]
Here's a screenshot of Toronto with the new chart, you can see under the time it's "Tue" with the new chart as well.
<img src="https://github.com/Akylas/oss-weather/assets/112411524/3fc32424-f474-4c56-a0ef-600dd3283488" width=40% height=40%>

**Comment by farfromrefug** [comment]
@0-5-0 great explanation! thanks will look at that tomorrow

**Comment by farfromrefug** [comment]
@0-5-0 should be better in latest. let me know

**Comment by 0-5-0** [comment]
Looks great now, thank you :)
