### ISSUE TITLE
Main page new chart doesn't show line for wind speed?

### ISSUE THREAD

**Issue by 0-5-0** [Akylas/oss-weather#175]
Should the new main page chart show a line for wind speed? I can tap the chart on the main page to see what the wind is but I might have expected that wind would show up like it does under Settings -> Chart.

<img src="https://github.com/Akylas/oss-weather/assets/112411524/1ef73892-2eee-4aca-993c-8cfc7159abc2" width=50% height=50%>

**Comment by 0-5-0** [comment]
It's not possible to have the old chart be configurable where we could select having it display 3 hour intervals instead of 1 hour? I'm thinking to avoid duplication so you're not having to maintain multiple charts.

**Comment by farfromrefug** [comment]
@0-5-0 could be possible. But i dont mind managing both. It is cool to have people be able to customize the app to their need.
