### ISSUE TITLE
Incorrect build numbers

### ISSUE THREAD

**Issue by jacobgonzales20** [Akylas/oss-weather#177]
Incorrect build numbers are being reported on the app and the GitHub, this might cause confusion for debug issues.

## GitHub
<img width="879" alt="image" src="https://github.com/Akylas/oss-weather/assets/122128828/4036c594-a0d6-4997-8316-69f12b37eb12">

## App Store
![app store](https://github.com/Akylas/oss-weather/assets/122128828/7fc34b84-0ddf-4395-916b-1e1a4e98f25f)

## App Settings
![app 2 3 0](https://github.com/Akylas/oss-weather/assets/122128828/f6220099-3593-46f3-92d2-7b7f5e90296b)

**Comment by farfromrefug** [comment]
@jacobgonzales20 It  is "normal". right now Android/iOS versions are not at the same pace and are not at the same buildnumber/version. 
The github release is made during the android release so it contains the android changelog.
I might look at making github releases for iOS and Android (separated) but the ios releases would only be there for reference (changelog). Will think about it

**Comment by farfromrefug** [comment]
@jacobgonzales20 is that ok if i close this for now?

**Comment by jacobgonzales20** [comment]
> @jacobgonzales20 is that ok if i close this for now?

Yeah, I will close
