### ISSUE TITLE
Don't prompt for API key on every launch

### ISSUE THREAD

**Issue by julianfairfax** [Akylas/oss-weather#18]
I know having my own API key would be better, but having a popup at the bottom say that every time I open the app makes it annoying to use

**Comment by farfromrefug** [comment]
@julianfairfax I understand that. But also if you keep on using the default one it will soon get over the rate limit (as the app get used more) and so you ll get an error on every single request and no weather data ;)
I honestly think the trade off is better. The one thing I could fix is to show it only on app start and not resume (might already be the case). So don't close the app to see it only once
