### ISSUE TITLE
temperatures are off

### ISSUE THREAD

**Issue by jacobgonzales20** [Akylas/oss-weather#181]
Temperatures displayed in main view are off
![hourly charts](https://github.com/Akylas/oss-weather/assets/122128828/aaa3d8fd-f033-4255-a248-643f0435c753)

**Comment by farfromrefug** [comment]
@jacobgonzales20 can you please share the location you are using?

**Comment by jacobgonzales20** [comment]
> @jacobgonzales20 can you please share the location you are using?

Grand Rapids,MI

**Comment by farfromrefug** [comment]
@jacobgonzales20 new version is in review. You should get it today

**Comment by jacobgonzales20** [comment]
> @jacobgonzales20 new version is in review. You should get it today

Issue is fixed in v2.3.2 Build 104
