### ISSUE TITLE
Separate selection of units of measurement

### ISSUE THREAD

**Issue by TenchMaviatorius2759** [Akylas/oss-weather#184]
I know there is a setting for "Imperial units of measurement", but I would like to be able to choose different units of measurement separately for each weather parameter.
For example, wind speed: meters per second or kilometers per hour, temperature: °C or F, and so on.

**Comment by farfromrefug** [comment]
@TenchMaviatorius2759 great idea will add that as soon as i can

**Comment by farfromrefug** [comment]
@TenchMaviatorius2759 it is now implemented
