### ISSUE TITLE
Export settings crash

### ISSUE THREAD

**Issue by ghost** [Akylas/oss-weather#186]
Export settings has a crash when pressed on iOS

v2.3.2 Build 104

Update: Crash is still apparent in 2.3.3 Build 105

https://github.com/Akylas/oss-weather/assets/122128828/2e4eb908-389a-4f4d-89ab-cc528666eaf4

**Comment by farfromrefug** [comment]
@jacobgonzales20 thanks i got your crash report but i dont know what s happening. Will try to reproduce.
Thanks
