### ISSUE TITLE
Macabre/violent messaging partly hidden inside the app

### ISSUE THREAD

**Issue by Mrnofish** [Akylas/oss-weather#188]
When consulting the weather map, there is a link in the right, lower corner that opens a message signed by the Leaflet devs.

This message makes an overt reference to the sunflower seeds video, which portrays a Ukrainian lady confronting a Russian soldier and finally giving him seeds to put in his pockets.

The meaning is that when the Ukrainian Army will have killed all Russian soldiers, their bodies will serve as compost bags for the seeds to grow.

Half-way through the message, the text asks the reader to donate money to Ukrainian charities and later claims "if this appeal to humanity doesn't work for you", and goes on to explain how that's tantamount to supporting the Russian Invasion of Ukraine and the reader deserves to die too (carry some seeds in your pocket).

Naturally, there's nothing bad about spreading awareness or asking for donations.

However, the message relies on violent and macabre imagery, and the way it reads is a kind of moral blackmail, which is also quite objectionable.

Impressionable kids could be exposed to this messaging without their parents noticing, since the text is partly out of sight and the app is otherwise family-friendly.

**Comment by farfromrefug** [comment]
@Mrnofish Thanks for reporting this. I agree with you just about the fact that i dont want my app to have a political message, whatever my beliefs are.
I still want to attribute leaflet. I just changed the attribution to point the leaflet github webiste
