### ISSUE TITLE
[2.4.4. Build 123] Weather provider resetting in seemingly random fashion

### ISSUE THREAD

**Issue by Mrnofish** [Akylas/oss-weather#189]
Since installing 2.4.4 Build 123 I've had two instances of the data provider resetting to Meteo France from Open Meteo.

The first time it was right after installing the upgrade. The second one today, after forcing a manual refresh.

After taking a look at a filtered logcat, I did not find much of relevance, other than the activity has been resumed/restarted from background, as apparently I had used the app about 90 minutes prior.

**Comment by farfromrefug** [comment]
@Mrnofish I suspect it is not random but because of a hidden feature. If you swipe left/right on the actionbar(location name) then it switches provider. 
Could it be that ?

**Comment by Mrnofish** [comment]
I didn't do it on purpose (first I hear of this feature) and I cannot rule out that it wasn't some mishap. I'll pay extra attention now that I have been made aware.

Since the provider can be changed that way, perhaps you should have that piece of information displayed somewhere in the main screen.

**Comment by farfromrefug** [comment]
@Mrnofish you are right. I dont want to clutter the main view so i ll make it a setting disable by default!
If you think there is still an issue not coming from that feature please let me know and i ll take a deeper look

**Comment by Mrnofish** [comment]
The issue didn't present itself after the switch was introduced, so I'm guessing your diagnosis was correct.

Closing with many thanks.
