### ISSUE TITLE
Favorites don't display

### ISSUE THREAD

**Issue by jacobgonzales20** [Akylas/oss-weather#190]
Locations that are favorited don't show as favorited. The star becomes unstarred. 

https://github.com/Akylas/oss-weather/assets/122128828/32667650-3a37-461a-9c50-f51bcd849c3c

**Comment by farfromrefug** [comment]
@you are using thé option To run à GPS check on every pull.to refresh? If so it is normal the location  might be différent everytime (GPs won't always return the same location)

**Comment by jacobgonzales20** [comment]
> @you are using thé option To run à GPS check on every pull.to refresh? If so it is normal the location might be différent everytime (GPs won't always return the same location)

yes

**Comment by farfromrefug** [comment]
@jacobgonzales20 then I can't do much about it. That is a limitation to the feature you asked for ;)
