### ISSUE TITLE
The unreadable status bar in the black theme

### ISSUE THREAD

**Issue by TenchMaviatorius2759** [Akylas/oss-weather#194]
v2.5.0.124 Android 13
When switching to the black theme, the status bar also turns black, which makes it unreadable.

https://github.com/Akylas/oss-weather/assets/140940260/5d6a6c56-b715-4d6e-8ca0-b66f74fb5822

**Comment by farfromrefug** [comment]
@TenchMaviatorius2759 thanks a lot will be fixed in next version!
