### ISSUE TITLE
Meteo France main model innacurate

### ISSUE THREAD

**Issue by bonswouar** [Akylas/oss-weather#198]
I've been trying to check which of the models is the more accurate in my area (I love the compare models feature!!), and I've noticed the main Meteo France model is always much higher in temperatures than all others.

Digging a bit more, I've enabled all Meteo France models from Open-Meteo to find out which one is used by default, and it still doesn't correspond to any:
<img src="https://github.com/Akylas/oss-weather/assets/615053/dbfb46c7-8274-40e6-a9e3-fe15cc7e34a7" width="480">

I've also compared to another weather app that uses Meteo France by default, and it's much more accurate (probably Arpege?):
<img src="https://github.com/Akylas/oss-weather/assets/615053/ea9825e4-2489-426a-bdfc-f25af19770b7" width="350">

As temperature is pretty much always higher, I wonder if there isn't something wrong with location when calling the API?

**Comment by farfromrefug** [comment]
Breezy and oss-weather use the exact same météo France API. Still if you can share a screenshot of the difference between metro France in both apps (full screen so that I also see the location) that could help.
As for météo France in open météo data. It is not comparable. You are comparing raw model data (open météo) with pre processed data(météo France). 
Thé bad thing with météo France is that we are using (all apps) an undocumented API for which we can't get support.

Finally please share if you find data incoherence. I personally dont see it(using météo France as I leave in France) but that does not mean there is not.

**Comment by bonswouar** [comment]
> As for météo France in open météo data. It is not comparable. You are comparing raw model data (open météo) with pre processed data(météo France).

Got it, I didn't think there wasn't any "post processing" from Open-Meteo when using Météo France data

> (full screen so that I also see the location)

I'd prefer not to share it publicly as my location is a very small village 😄 

But here is a comparison of the two apps after setting the model to Météo France:
<img src="https://github.com/Akylas/oss-weather/assets/615053/083fca0b-1962-4981-9311-7a9aa25d8fb5" width=320>
<img src="https://github.com/Akylas/oss-weather/assets/615053/7bdac08b-0afd-458e-b186-4b63c23c7b01" width=320>

It seems the incoherence is real, but only in the hourly data!

**Comment by farfromrefug** [comment]
@bonswouar open météo is not in a sense processing météo France dats. But meteo France provider is. So open météo Météo-France data is not comparable with Météo-France provider (days coming directly from Météo-France website).

About you screenshots the difference seems crazy. Are you using Météo-France provider in breezy?

**Comment by bonswouar** [comment]
> About you screenshots the difference seems crazy. Are you using Météo-France provider in breezy?

Yeah it is crazy, that's why I opened an issue 😄 
That's basically the same difference you can see on the Compare graph screenshot, pretty much always 3 to 5 °C higher than other models

And yes I'm sure both use Météo France (as you can see the daily data are the same)

<img src="https://github.com/Akylas/oss-weather/assets/615053/28683c3e-aeea-4a44-9d9f-cea90fbcb44f" width=320>
<img src="https://github.com/Akylas/oss-weather/assets/615053/1a91f2f3-784e-454c-b000-c38213d40b90" width=320>

And the proof ;)
<img src="https://github.com/Akylas/oss-weather/assets/615053/2754013d-f516-4858-980f-7e4972e293b9" width=320>

**Comment by farfromrefug** [comment]
@bonswouar ok that is really weird. Just tried here with Grenoble and the datas from both apps are "synced". The only difference in hourly data comes from rounding temperature values. But it should never more than 1 difference.
Could you share your location privately ? my mail is dev at akalyas dot fr

**Comment by bonswouar** [comment]
After more testing it could indicate the problem might be from lat/lng location. But it would need more testing and a way to easily reproduce...
Meanwhile my fix was to clear app data, and add again my location (by searching from it instead of using actual gps), there is no temperature discrepancy anymore
![1011-1024-max](https://github.com/Akylas/oss-weather/assets/615053/038b0950-8b7f-40de-af04-6a215111489e)
