### ISSUE TITLE
Feature request: Toggle to show precipitation percentage in hourly chart when it's not raining

### ISSUE THREAD

**Issue by CypherNL** [Akylas/oss-weather#207]
**Platform:** iOS
**OSS Weather version:** 2.6.1

Currently, on the hourly chart, the precipitation percentage only shows when it's raining. 

Since the precipitation percentage can still be higher than 0% when it's not raining, i would like to see a toggle in the settings menu to always show the precipitation percentage in the hourly chart as i find it useful information regardless. 

Currently, the workaround is to go to "Compare Charts" and only show the best match model of Open-meteo, which is quite cumbersome.

**Comment by farfromrefug** [comment]
@CypherNL nice idea. I ll have to see how i "represent" this for it not to be mistaken for actual precipitation

**Comment by farfromrefug** [comment]
@CypherNL It is now released!

**Comment by CypherNL** [comment]
I’ve updated the app and enabled the option. It does work as I've described. Thanks for adding the feature!
