### ISSUE TITLE
tablet support

### ISSUE THREAD

**Issue by wynteryyc** [Akylas/oss-weather#208]
Hi

I would love to run this on my Pixel tablet but I can't install it from F-Droid on my tablet.  there's no option to install it when I am on my tablet.

**Comment by farfromrefug** [comment]
@wynteryyc this must be because your tablet is using an old arch armv7. Right now izzydroid only sees armv8 build. 
So your best solution is to install from github and use obtainium to check for updates

**Comment by wynteryyc** [comment]
on a new pixel tablet? gonna check now, thank you.👍🏼

Dale Forrest
https://sacredpeak.ink

-------- Original Message --------

**Comment by farfromrefug** [comment]
@wynteryyc OK if new tablet then could be x86 can you check your tablet arch ?

**Comment by wynteryyc** [comment]
Google Tensor G2

Dale Forrest
https://sacredpeak.ink

-------- Original Message --------

**Comment by farfromrefug** [comment]
@wynteryyc that s the chip yes. I need the "abi" of your tablet. Here is what i am talking about https://android.stackexchange.com/questions/224532/how-to-check-android-phone-s-processor-arm-arm64-or-x86

**Comment by wynteryyc** [comment]
here you go

Dale Forrest
https://sacredpeak.ink

-------- Original Message --------

**Comment by farfromrefug** [comment]
@wynteryyc sorry but i dont understand what you mean by here you go ? Can you try and find your tablet abi so that i can add it to my builds?

**Comment by wynteryyc** [comment]
Hi

I attached a screenshot in my reply, which I think you didn't get; this is why my reply looked flippant. sorry.

I think what you are looking for is: ARM64-V8A

Thanks!

Dale Forrest
https://sacredpeak.ink

**Comment by farfromrefug** [comment]
@wynteryyc ok so it is armv8a which the default i publish on izzydroid.
* are you using izzydroid repo in F-Droid?
* what does F-droid tells you when you are on the app's page?

**Comment by wynteryyc** [comment]
hi.

in Droid-ify it shows 'requires android.hardware.location.gps'

I run GrapheneOS on tablet and phone. pixel 8 pro phone works to install. I can install it noproblem on the tablet if I download directly from GitHub.

Dale Forrest
https://sacredpeak.ink

-------- Original Message --------

**Comment by wynteryyc** [comment]
I never even noticed those notes under the versions til you asked

thanks for fixing this

Dale Forrest
https://sacredpeak.ink

-------- Original Message --------
