### ISSUE TITLE
Weather alerts not showing up

### ISSUE THREAD

**Issue by exstntlmsnthrp** [Akylas/oss-weather#21]
When the top of the app indicates there is a severe weather alert, tapping on the alert shows a blank popup. For example, today we have a storm (which I don't need the app to see) and I want to tap the severe weather alert to learn how long they estimate the storm will last and what the conditions will be. See image. 

Device: Pixel 7 Pro
Android: 13
App version: 1.3.2.50
App source: F-droid

![Screenshot2.2.2.png](https://user-images.githubusercontent.com/57594290/221873981-c58bb990-527e-4bc0-a70a-38faa4f18a31.png)

**Comment by farfromrefug** [comment]
@exstntlmsnthrp thanks a lot I ll fix it very soon!
