### ISSUE TITLE
[Bug] meteoblue 7 days wrong location

### ISSUE THREAD

**Issue by azertylr** [Akylas/oss-weather#211]
Hello,

Thanks again for this awesome app:)

The 7 days meteogram from meteoblue is always at "Bale" location and not and the specified location.

The metrogram and all in one are fine.

Best

**Comment by farfromrefug** [comment]
@azertylr good catch! Sadly meteoblue changed their website. I cant get the one for your location anymore. Would need Meteoblue Point+.
Will have to remove the 7 days meteogram :s

**Comment by azertylr** [comment]
You could create your own :)
Their is this app for custom meteogram https://play.google.com/store/apps/details?id=com.cloud3squared.meteogram

**Comment by farfromrefug** [comment]
@azertylr i kind of already do in the "chart" view.
The meteoblue point is to be able to get meteoblue forecast

**Comment by azertylr** [comment]
> you are right :)

**Comment by azertylr** [comment]
Wrong button
