### ISSUE TITLE
Add Option to display both Metric and Imperial units

### ISSUE THREAD

**Issue by Batcastle** [Akylas/oss-weather#212]
Hello there! I would like to have an option both metric and imperial units displayed. I live in the USA, where imperial units are most often used, but I am trying to get myself more familiarized with Metric. Having both units displayed would be very useful for that, and for people who travel abroad often.

Is having this added a possibility?

Thank you!

**Comment by farfromrefug** [comment]
@Batcastle I don't i will add such a feature. It would require a major rewrite, but also rethinking the whole layout (cause it would obviously take more place) for a very specific use case.
i hope you understand.

**Comment by farfromrefug** [comment]
@Batcastle not sure if it can solve your issue but now you can define each units using imperial or metric
