### ISSUE TITLE
Show "feels like" temperature as separate value

### ISSUE THREAD

**Issue by QuantumQuacken** [Akylas/oss-weather#213]
Hello!
I wonder if it might be possible to have a toggle that would allow the "feels like" temperature to be displayed alongside the measured temperature, rather than overwriting it. Alternatively, could it be added as an additional field that can be enabled in the Weather Data preferences?

Thank you!

**Comment by farfromrefug** [comment]
@QuantumQuacken i will add it as a separated weather data field. Wont have layout consequences

**Comment by QuantumQuacken** [comment]
Sounds good! Thank you a lot!

**Comment by farfromrefug** [comment]
@QuantumQuacken it has been implemented. And i will release a new version which allows to see apparent min/max for daily forecast when available

**Comment by QuantumQuacken** [comment]
> @QuantumQuacken it has been implemented. And i will release a new version which allows to see apparent min/max for daily forecast when available
> EDIT: released

Looks amazing and correct! Thank you!
