### ISSUE TITLE
Bad hour details panel z-placement

### ISSUE THREAD

**Issue by Caellian** [Akylas/oss-weather#214]
Popup panel is displayed under hours columns.

[![bug preview](https://i.imgur.com/DUaSFri.png)](https://imgur.com/a/4PqDBTb)

Version: 2.6.4 build 130
Android Version: 13 w/ default Google spyware

**Comment by farfromrefug** [comment]
@TenchMaviatorius2759 thanks for reporting. SHould be fixed in latest version
