### ISSUE TITLE
Quick Start Guide

### ISSUE THREAD

**Issue by garudaonekh** [Akylas/oss-weather#216]
Hi,
I am new to Svelte and Native script. I have some experience with ionic+capacitor.

I try to get this up  and running. As I go through the issues list, this one use PNPM instead of NPM.

I can successfully run **`pnpm install`**. After that I try to run.
```
pnpm run build.android.production
 WARN  The "workspaces" field in package.json is not supported by pnpm. Create a "pnpm-workspace.yaml" file instead.
```

Would you mind writing a small quickstart guide for rookie?

**Comment by farfromrefug** [comment]
@garudaonekh pnpm is not really "supported". It should work but i dont use it anymore so i cant really say what should be added/changed.
I updated the readme with basic setup config and launch command. You should use yarn  >= 4.x with this project
Let me know if you face any issue

**Comment by garudaonekh** [comment]
> @garudaonekh pnpm is not really "supported". It should work but i dont use it anymore so i cant really say what should be added/changed. I updated the readme with basic setup config and launch command. You should use yarn >= 4.x with this project Let me know if you face any issue

Thanks.

I saw in one of your issue response saying that you use pnpm that's why I tried pnpm.
[https://github.com/Akylas/oss-weather/issues/3#issuecomment-699794578](https://github.com/Akylas/oss-weather/issues/3#issuecomment-699794578)

**Comment by garudaonekh** [comment]
I try to use Yarn but failed with dependency errors and missing package, i try to reinstall several but still error.
 This git has many plugins(webpack, nativescript webpack@your own git,  svelte....).

A quick installation guide would definitely help.

**Comment by farfromrefug** [comment]
@garudaonekh i updated the readme with basic setup instructions
