### ISSUE TITLE
Messed up display

### ISSUE THREAD

**Issue by cycyx** [Akylas/oss-weather#22]
When used in portrait mode, the sunset hours and last update words get mixed up (in french).
![Screenshot_2023-03-10-00-31-53-74_1c70c3151298b10f38162db1fcf1d3d5](https://user-images.githubusercontent.com/3910864/224184315-1fa0ff32-af98-48a4-b026-51f953dd1e25.jpg)

**Comment by cycyx** [comment]
Wider view (it happens when update time has a weekday) :
![Imagepipe_20](https://user-images.githubusercontent.com/3910864/224184890-d489d105-ec1b-4bf1-87be-23022855bb12.jpg)

**Comment by farfromrefug** [comment]
@cycyx can you give me your phone specs? I will fix the layout /text in French so that it works better

**Comment by farfromrefug** [comment]
@cycyx should be fixed now, i made text "shorter" to prevent that
