### ISSUE TITLE
[2.7.0.133] Daily forecasts show incorrect dates

### ISSUE THREAD

**Issue by Mrnofish** [Akylas/oss-weather#223]
After installing 2.7.0.133, daily forecasts on the main screen are displaced.

The current day appears in the list, so the first forecast is labeled "Fri Sep, 6" (today's date) - the data which follows is actually the forecast for Sat Sep, 7 (tomorrow).

All subsequent days are the same, so the forecast for Sunday is labeled as Saturday, and so on.

**Comment by farfromrefug** [comment]
@Mrnofish sorry about the issue. Any chance you can share a screenshot ?

**Comment by Mrnofish** [comment]
I'm not too keen on disclosing my location, besides you can only notice the difference if you knew what the forecast was before the update.

The only obvious to anybody difference (if I'm not mistaken) is that previously the current day wouldn't be listed in the forecast, i.e. the list began from the following day.

**Comment by farfromrefug** [comment]
> I'm not too keen on disclosing my location, besides you can only notice the difference if you knew what the forecast was before the update.
> 
> The only obvious to anybody difference (if I'm not mistaken) is that previously the current day wouldn't be listed in the forecast, i.e. the list began from the following day.
> 
> PS: nevertheless I'll try to edit a screenshot whenever I get some computer time.

I 100% understand. can you add any location like new york and share how it looks like?

**Comment by Chartrux** [comment]
Hi, 
Same issue here
First screenshot is 2.6.6.132 : current day is sunday, first day in list is monday
![Screenshot_20240908-080004_1](https://github.com/user-attachments/assets/0a3df5c2-6b07-40bb-8f1b-31c8e74bbfb2)

Second screenshot is 2.7.0.133 : current day is sunday, first day un list is saturday
![Screenshot_20240908-080114_1](https://github.com/user-attachments/assets/fd674a23-830a-454f-9220-a3c0831839ad)

**Comment by Atrate** [comment]
I can confirm this as well. Some sort of off-by-one error? E.g. today is Sunday but the forecast for today is labeled Saturday.

**Comment by farfromrefug** [comment]
Sorry To all of you. I see the regression now. Will fix tomorrow. 
The day is offset by -1.
Sorry about that

**Comment by Mrnofish** [comment]
While I was testing locations for a screenshot, I found some that were actually offset by more than 1.

It could be related to a combination between time of the day, the device's timezone, and the location's.

As most users probably only check the weather for locations that are sufficiently close one to another in terms of timezone, the issue might be unrelated and undetected until now.

To try reproducing, select a location that is west from your reference, and across the midnight line, i.e. it should be yesterday (say Sunday) still in the test location, compared to your offset 1 reference (where it's already Monday).

**Comment by farfromrefug** [comment]
@Mrnofish Be careful if you choose locations far from you. They are using "local" time.

@Atrate @Mrnofish @Chartrux i released a new version which should fix this

**Comment by Atrate** [comment]
I can confirm that this is solved now. Thanks!
