### ISSUE TITLE
Map animation is a touch too fast

### ISSUE THREAD

**Issue by Mrnofish** [Akylas/oss-weather#227]
The map animation is a touch fast for my tastes, it makes interpreting the movement of the rain cells harder than it needs be. Would it be possible to perhaps add some way to customize the speed?

**Comment by farfromrefug** [comment]
@Mrnofish sure i ll make it configurable!

**Comment by farfromrefug** [comment]
@Mrnofish it is now implemeneted

**Comment by cb8121** [comment]
Hi, after the Implementation in v2.8.1 the map isn't working any more.
![Screenshot_20241029_104134_OSS Weather](https://github.com/user-attachments/assets/78de4356-ec3a-496d-adfb-6f9d5c98114b)

**Comment by Mrnofish** [comment]
FWIW it's working for me. There is some room for small improvements (e.g. the slider setting a delay value?) but it's fine otherwise, thanks for taking care of it.

(I'm leaving this open since it's being used to track the regression.)

**Comment by farfromrefug** [comment]
@Mrnofish indeed the animation speed is defined by a delay. Would it be better to have a speed like with default to 1 and the going slower (0.5) or faster (1.5) ?

**Comment by Mrnofish** [comment]
Since the proposed scale would be completely arbitrary (real time not being a useful option), it would come down to the tuning. 

What I was pointing out, is that a slider labeled "speed" intuitively associates bigger numbers to higher speeds, whereas now it works in reverse (in fact sliding to the right, which is generally associated with higher/louder/faster/etc, causes the animation to slow down instead.)

I can certainly live with the way it is, though, and simply renaming the slider so that it's consistent with its function would probably be okay for most.

**Comment by farfromrefug** [comment]
@cb8121 I am.sorry I can't see what s happening. Was it working before ?
Where did you install it from ? Maybe you could share a logcat?

**Comment by farfromrefug** [comment]
@cb8121 i found the issue will fix!

**Comment by 0-5-0** [comment]
Map/not found issue seems to be resolved now in both the latest (build 144) Google Play Store and the Github versions.
