### ISSUE TITLE
Granular metric Vs imperial settings equest

### ISSUE THREAD

**Issue by oscott** [Akylas/oss-weather#228]
Hello. As a person from England I have been brought up with miles as a measure of distance, centigrade as temperature and all sorts of other nonsense. In Oss weather preferences the whole system has to be either metric or imperial. Is it possible to chose a preference per item? Thanks. This is the best weather app I have used. And I've tried a lot.

**Comment by farfromrefug** [comment]
@oscott sure thing will add fine grained units settings

**Comment by farfromrefug** [comment]
@oscott just released a new version with the feature implemented. Look in settings/units

**Comment by oscott** [comment]
Its perfect. Thank you. Now the best weather app out of many, is even better.
