### ISSUE TITLE
CO pollutatns skewing AQI score

### ISSUE THREAD

**Issue by Atrate** [Akylas/oss-weather#229]
Hello,

Wherever I look in the app (pretty much regardless of location), the carbon monxide (CO) values are always really high, skewing the calculated AQI a lot.

![image](https://github.com/user-attachments/assets/ac675a4f-c816-4835-a5b0-1ee4c0bf980f)

Is this this way on purpose? Maybe the calculations should be adjusted somehow?

**Comment by farfromrefug** [comment]
@Atrate i saw the same thing yesterday will try to investigate

**Comment by farfromrefug** [comment]
@Atrate just released a new version which should fix it

**Comment by Atrate** [comment]
Seems to be fixed, thanks!
