### ISSUE TITLE
[UI Bug] Precipitation Icon Rounding Issue

### ISSUE THREAD

**Issue by LinuxinaBit** [Akylas/oss-weather#237]
Along with various UI overlap issues, the precipitation number is not rounded at _least_ in the weekly view:

![Screenshot_20241115-120115-711](https://github.com/user-attachments/assets/c6829356-9f60-4d94-8b39-56954cb9c5d9)

Android 10
Motorola Moto G Power (2021)
App from IzzyOnDroid F-Droid repo
Version 2.8.2 Build 139

**Comment by farfromrefug** [comment]
@LinuxinaBit sorry it is a regression!

**Comment by LinuxinaBit** [comment]
Ah, it's alright :)

**Comment by 0-5-0** [comment]
This seems to be working well now in the latest release.
