### ISSUE TITLE
Interface is all tinted black

### ISSUE THREAD

**Issue by jgonzales20** [Akylas/oss-weather#239]
![IMG_9949](https://github.com/user-attachments/assets/e7deaf1d-19cb-4c35-ac46-f041528bda28)
![IMG_9950](https://github.com/user-attachments/assets/e5c95fe9-e0d5-4633-8839-47e2587311c2)
![IMG_9951](https://github.com/user-attachments/assets/76666f6f-2b2b-4e98-9a3f-0f6b75cd157d)
![IMG_9952](https://github.com/user-attachments/assets/6a46a9c8-d22e-464e-9d9b-23fee2f00f94)

**Comment by farfromrefug** [comment]
@jgonzales20 ios i suppose?

**Comment by jgonzales20** [comment]
That is correct, uploaded this from my phone. Here's more details,

Build 2.8.2 Build 118
IOS 18.1
IPhone 14 Pro.

On a side note, please allow photo upload for the in app feedback form.


________________________________

**Comment by farfromrefug** [comment]
@jgonzales20 thanks publishing a new version with the fix!

**Comment by jgonzales20** [comment]
Thank you, I use this app daily.


________________________________
