### ISSUE TITLE
Add material you theme ?

### ISSUE THREAD

**Issue by MXC48** [Akylas/oss-weather#24]
I think that adding material you I think that adding material U to the application will modernize it more and therefore to make it fit better into the rest of the system
Thanks !

**Comment by farfromrefug** [comment]
@MXC48 still on Android 10 but i can look at it ;)

**Comment by MXC48** [comment]
> @MXC48 still on Android 10 but i can look at it ;)

Thank you very much!

**Comment by farfromrefug** [comment]
@MXC48 it has been implemented
