### ISSUE TITLE
Wrong unit for snow forecast: "distSmall"

### ISSUE THREAD

**Issue by cb8121** [Akylas/oss-weather#240]
Hello, in case of snow there ist a strange unit "distSmall" shown, should be mm or cm instead:
![Screenshot_20241120_084528_OSS Weather](https://github.com/user-attachments/assets/76d73073-6bc0-4927-b3ac-15b1ddffd207)

**Comment by farfromrefug** [comment]
@cb8121 just released a fix! thanks for reporting

**Comment by 0-5-0** [comment]
I had that same issue and it was fixed. I'm guessing it could be closed.
