### ISSUE TITLE
Map not found on Android

### ISSUE THREAD

**Issue by fattybenji** [Akylas/oss-weather#245]
Hello !

When opening the map, I get the following error message (in french):

```
Impossible de charger la page Web file:///data/data/com.akylas.weather/files/app/assets/map/index.html?zoom=8&animated=false&animationSpeed=100&colors=1&position=48.9148269,2.2674892&mapCenter=48.9148269,2.2674892&owm_key=f6b8f6a582a555904b914aa9cc6f12e4 pour la raison suivante :

net::ERR_FILE_NOT_FOUND
```

This might be related to this [recent change](https://github.com/Akylas/oss-weather/commit/993667c95b453a7286fa463c3f1391a7b119ca0b#diff-a5354ce87290d945a99121dbc0f1d881975f4c7639882fc0196bdd80ba4a71ad) ? Maybe an issue with the path [here](https://github.com/Akylas/oss-weather/blob/6484c83973270aaf3772b9b28088a6e216ecb153/map/webpack.config.js#L11) ?

App version: 2.8.4
Device: Fairphone 5/Android 14

**Comment by farfromrefug** [comment]
@fattybenji this is really strange. Wondering if it could be a permission issue:
* was it working in older versions?
* can you actually browse to that folder and see if that file exists?
* Where did you install it from?

**Comment by 0-5-0** [comment]
I get the same error on Android, it seemed fixed in 2.8.5 but returned in 2.9.0. I'll periodically switch between the Playstore and Github versions, currently it's the Playstore version that's installed.

Side note and maybe related, if I open the app, go to Settings -> Map, then choose a Weather map color scheme, it skews the schemes by 1. If I select NEXRAD, it shows RAINBOW one I go back to the Settings -> Map page. This might be causing issues with the loading the proper map?

**Comment by 0-5-0** [comment]
Here's a screenshot, also trying to select the color scheme from this menu isn't working, I press TITAN for example, the pop up menu closes but if I re-open it it's still stuck on NEXRAD.

<img src="https://github.com/user-attachments/assets/9127d390-37f8-476a-885a-993ed03efb2a" width=50% height=50%>

**Comment by 0-5-0** [comment]
Map/not found issue seems to be resolved now in both the latest (build 144) Google Play Store and the Github versions.

**Comment by fattybenji** [comment]
Thank you for the updates, sorry I didn't answer before (notification issues). I had an experience similar to 0-5-0, worked before, and I messed around with the themes lately but never noticed the offset. And I installed from the Play Store.

Looks fixed for me now so I'm closing the issue.

Thank you very much for the quick fix !
