### ISSUE TITLE
UV index by hour

### ISSUE THREAD

**Issue by droserasprout** [Akylas/oss-weather#248]
For some regions per-hour data about UV index is essential to plan a day. I used `de.beowulf.wetter` app to access this data. For reference, here's how it looked like:

![Screenshot_20241127-122854_Weather](https://github.com/user-attachments/assets/198df100-d6e9-4972-bab9-ef2a15e133c0)

Unfortunately, this app has been deprecated when OpenWeather started requiring credit card for the new API.

Nice to haves for UV index data:

- Color coding (see "Index usage" here: https://en.m.wikipedia.org/wiki/Ultraviolet_index)
- An option to show UV index on graphs. But any UI would be great.

**Comment by farfromrefug** [comment]
@jazzzz thanks i will look into it. But it would be available only if the weather providers (open-meteo, meteofrance...) provides it.

**Comment by farfromrefug** [comment]
@droserasprout it is available in latest version. Click on an hour to see the popup with uvIndex (when available).
I made the choice to show a rounded value. Dont think the float value as much value

**Comment by 0-5-0** [comment]
It's working well for me in the hourly view, in the hourly popup view, as you said "when available" depending on the model it's not listed (ECMWF didn't show it for my region, but GFS does).

**Comment by droserasprout** [comment]
Thank you so much, guys!
