### ISSUE TITLE
Completely wrong Sunrise/Sunset

### ISSUE THREAD

**Issue by kokesh** [Akylas/oss-weather#255]
Sunrise at Vedjeön, Sweden right now is 9:27, Sunset at 14:11.
OSS reports 1037/1504.

**Comment by farfromrefug** [comment]
@kokesh i just tested and the values are 9:37 and 14:02 . Those values seem quite ok to me. 
What i am thinking with what you see is a timezone issue. If i am not wrong your timezone is `Europe/Stockholm` and your time zone offset is 1 hour?
This is what it reports here for your location, and it displays find here.
Also how did you add that location? search or GPS?

**Comment by kokesh** [comment]
The weird thing is that it is not hour off, it is hour & some minutes. I found the location via GPS i think.

**Comment by kokesh** [comment]
It is correct now, I'm sorry. It found location somewhere else for some reason!

**Comment by kokesh** [comment]
Works now, my bad
