### ISSUE TITLE
Feels like apparent temperature icon showing same range as daily

### ISSUE THREAD

**Issue by 0-5-0** [Akylas/oss-weather#258]
The feels like/apparent temperature icon is showing the same high/low temperature range as the forecasted temperature range when you're looking at the daily list view.

At the top in the current forecast I see -6 celcius as feels like, the apparent icon also shows -6 celcius at the top, the temperature forecast shows -8/-3 at the top. Then when I scroll down to the daily list  near the bottom, it shows -8/-3 apparent next to the icon and forecasts -8/-3 temperature in the far right side for today's date (Thursday/Thursday), using Toronto, Ontario, Canada as a test.

<img src="https://github.com/user-attachments/assets/c9e770bb-a671-4b80-b637-85855da3067b" width=50% height=50%>

**Comment by farfromrefug** [comment]
How did you search your location?search of GPS?
I dont get the same values for toronto (through search) with OpenMeteo. Did you change the model?
And here apparent temps are different.

**Comment by farfromrefug** [comment]
@0-5-0 then it is an issue with the model. You can report it in open-meteo repo

**Comment by 0-5-0** [comment]
If I try GFS Seamless, GEM Seamless they all show the same issue as ECMWF, so it's an up stream/open-meteo bug in general for their "daily" feels like/apparent temperature data?

**Comment by 0-5-0** [comment]
I think in your initial implementation of the apparent temp icon it was showing only for the current weather section at the top which seemed to be fine (or "if available"), but 1-2 versions ago it was added to all the days in the daily view at the bottom however mirroring the forecasted temperature.

I've always thought that the "feels like" temp was unreliable/couldn't be calculated long term (past the current time/date).

**Comment by farfromrefug** [comment]
@0-5-0 i know what the issue is. You must have selected `show feels like temperature when available`. This is replace "temp" everywhere with apparent.
In latest versions apparent is now a weather data which can be shown with others. But if you add feels like and select the always use feels like toggle then you end up with twice the same value.

**Comment by 0-5-0** [comment]
Ahhhh, that makes sense then. I was under the impression that feels like was only available for the current day but I see now through wizardry that it's available for the full 7 days/in the temperature reading on the right.

So turning on "Show feels like temperature when available" does actually show feels like temp on the right side in the list and then the apparent icon would "duplicate" it. But it works fine and displays sanely with the "show feels like temperature" off.

So it's basically deciding if I want it shown everywhere, only in the apparent icon or in both.. now I understand :)
