### ISSUE TITLE
Wind speed above 50 is hard to read on dark mode

### ISSUE THREAD

**Issue by 0-5-0** [Akylas/oss-weather#259]
Wind gust when it seems to hit 50+ goes dark grey and is difficult to read on dark mode. Not sure if another colour could be chosen or even if it could stay on orange.

<img src="https://github.com/user-attachments/assets/c9e770bb-a671-4b80-b637-85855da3067b" width=50% height=50%>

**Comment by 0-5-0** [comment]
It's visible now in version 144, still not sure if it should just be orange like the 30-49KM/hr range, it shows up "white" now which is better than the black/dark grey but it would be the same color as the lower wind (0-29?) gust ranges?

**Comment by 0-5-0** [comment]
Like in this screenshot above, if any wind speed over 30KM/hr could go orange, even including the 50+ range.

**Comment by farfromrefug** [comment]
@0-5-0 not sure about this. Then it would get cluttered with wind gust and i am afraid wind gust would not be "as visible" that way

**Comment by 0-5-0** [comment]
sorry I think I meant to say wind **gusts** go orange/red. In the screenshot for thursday you can see under the 27km wind speed that there's the grey/black wind **gust** that you fixed a couple releases ago but now it's white in the latest release it's white, that's the one that should maybe go orange or red.

It looks odd now having 0-29km be white, 30-49km is orange and 50km+ goes back to white. Making the 30-49km range go higher to include the 50+ range so it's orange or making 50km+ go red would make more sense.

**Comment by farfromrefug** [comment]
@0-5-0 indeed you are right this is a bug!
