### ISSUE TITLE
Feedback form isn't working in-app?

### ISSUE THREAD

**Issue by 0-5-0** [Akylas/oss-weather#261]
It's difficult to confirm but I've sent a few bugs through the PlayStore version/feedback form in app over the last few releases and I'm not sure if they made it to you. It asks for my name, email, feedback then I click Submit and it says something along the lines of submitted however maybe it's going into a black hole :).

Just to avoid users from submitting feedback that goes unanswered, if you could take a look or possibly remove that feature.

Also, sorry for the flood of "issues" :D

**Comment by farfromrefug** [comment]
@0-5-0 i think i got your feedback from 10 days ago. Sorry it was i an new "design" of my reporting software. Will try to look more at it

**Comment by 0-5-0** [comment]
Ok, no worries then :)
