### ISSUE TITLE
Map view suggestions

### ISSUE THREAD

**Issue by Mrnofish** [Akylas/oss-weather#263]
Just a couple things I would love:

1. The ability to change the map's zoom. I'm on 2.9.1 b144, and the two-finger gesture doesn't seem to do anything, nor I can see a zoom slider anywhere?
2. Dark mode for the map. I always enabled this on the radar site I used to use (but OSSW's Map view is just so much more convenient), and IMO it's not only easier on the eye in low light, but also decodes better in almost every light condition.

**Comment by farfromrefug** [comment]
@Mrnofish zoom should be working. Was it never working or is it a recent bug?
As for the dark mode. What "dark" are you wanting? are you talking about map images? You want the map to be dark?

**Comment by 0-5-0** [comment]
I don't use the map often, I do remember zoom working at some point but did notice it wasn't working the last 2 releases at least, including the latest, on Android anyways.

**Comment by 0-5-0** [comment]
Seems to have broken in build 135, in build 134 it works perfectly fine.

**Comment by Mrnofish** [comment]
@farfromrefug to make sure I double checked: the feature's called Dark Base Maps.

Is the map feature something you're sourcing whole from an external provider?

**Comment by 0-5-0** [comment]
Zoom is working now in the latest version (145).

With regards to maps they come from OpenStreetMap? I'm not sure if they have "dark" base maps.

I guess otherwise the OSS Weather interface in the map view is framed in white when using dark mode (the color legend and play/slider area), the pop up areas (selecting the models or animation/layer settings) are dark.

**Comment by LinuxinaBit** [comment]
QuickWeather uses OSM Carto tiles for the base layer. They seem to load a lot faster, be higher resolution, and have really nice light and dark modes.
They *might* actually be vector tiles which would be pretty cool.

**Comment by Mrnofish** [comment]
I had a look under the hood, and the service mentioned earlier is using CartoDB for the dark basemaps.

Specifically, I think it's the "Dark Matter" style that can be seen on the repo's front page:

https://github.com/CartoDB/basemap-styles

**Comment by farfromrefug** [comment]
@Mrnofish @LinuxinaBit good catch. Did not know that source was "free". Will try it

**Comment by Mrnofish** [comment]
Looks great, thanks!
