### ISSUE TITLE
Add a legend for "snow" on the radar map?

### ISSUE THREAD

**Issue by 0-5-0** [Akylas/oss-weather#267]
You added the snow button which is awesome, I was wondering why there was random blue spots on the map rainviewer was providing and now I get it lol.. would it be possible to add a legend for that snow button next to the precipitation legend? I get that it's probably light blue, medium blue, dark blue I suppose?

The black map tiles and theme looks awesome by the way.

**Comment by farfromrefug** [comment]
@0-5-0 will be added in next version

**Comment by 0-5-0** [comment]
There's a typo when you expand the legend, it says "Light theme", when I'm guessing it should just say "Light", then Moderate, then Heavy. Looks great otherwise. Thank you!

or maybe it could say Light snow, Moderate snow, Heavy snow. Still happy either way though.
