### ISSUE TITLE
App says that my API key is invalid

### ISSUE THREAD

**Issue by MattRGX** [Akylas/oss-weather#29]
Hello,

I've created an account on OpenWeatherMap (free account) and get my Api key. 

It was 2 ou 3 days ago. Now on my account it says that the API key is "active".

But when i put it in the app, i got the message that my key is invalid. 

Thanks for your help.

**Comment by farfromrefug** [comment]
@MattRGX ok i ll give a look on my side.

**Comment by n5corp** [comment]
Same exact issue, on Android

**Comment by farfromrefug** [comment]
@n5corp @MattRGX i just tried with my key and it works. Does you key give you access to the onecall api?
Any chance one of you can share his key privately?

**Comment by MattRGX** [comment]
I took the free plan on openweathermap.

![image](https://user-images.githubusercontent.com/58740578/231977331-86138b09-e96e-472a-9c39-59dd0f0f8af9.png)

So i guess we don't have access to the onecall api with this free plan.

The other plan where we have access to the onecall api is also free.

But we need to put the credit card numbers to get the API because up to a certain point it's not free anymore. 
And obviously for security and money purposes, i don't want to put my credit card numbers on the OWM website.

**Comment by farfromrefug** [comment]
@MattRGX i LL take a look. It was not like that before. 
But I understand I wouldn't add my credit card either

**Comment by farfromrefug** [comment]
@MattRGX could you ensure there is no unwanted spaces in your apikey (like at the end) from the application settings.
It did just happened to me that copying from the  website i get a space at the end and end up with an invalid api key error

**Comment by MattRGX** [comment]
> @MattRGX could you ensure there is no unwanted spaces in your apikey (like at the end) from the application settings. It did just happened to me that copying from the website i get a space at the end and end up with an invalid api key error

I've just double checked again the API key and there is no extra space or unwanted spaces at the beginning or at the end.

**Comment by farfromrefug** [comment]
@MattRGX thanks i still made a new release with a fix for that (and other fixes).
as for my i use the base plan.Is it the same for you? I even tried to generate a new key and it is working
<img width="857" alt="Screenshot 2023-04-15 at 09 38 23" src="https://user-images.githubusercontent.com/655344/232196390-98fff673-f33c-4d10-b267-548b7a93af5e.png">

**Comment by MattRGX** [comment]
@farfromrefug i use the free plan that is available in the "Professional collections" subscription plan.
I'm not using the other free plan that is available in the "One call by call" subscription plan.

**Comment by farfromrefug** [comment]
<img width="956" alt="Screenshot 2023-04-15 at 10 18 37" src="https://user-images.githubusercontent.com/655344/232200162-b30c65c4-deab-4047-9b1a-36b658775275.png">
I guess i have the same.
Could you share your. key privately? My mail is dev at akylas dot fr

**Comment by abalteaux** [comment]
FYI I'm on the same plan and I have the same issue, although I can query the API directly just fine with my key.

**Comment by farfromrefug** [comment]
@abalteaux which API  can you query directly?
I think owm changed the free tier and the one call api is not available anymore.
I am working on a new free weather provider

**Comment by farfromrefug** [comment]
@abalteaux  not the same api. I could switch to use multiple api calls but I would prefer not to.

**Comment by xerves78** [comment]
i have the same problem :(

my free api key is unvalid and doesnt work in the app :(

how can i fix it ?

**Comment by farfromrefug** [comment]
@xerves78 sadly it seems we can't . this JS why I added open-meteo provider which will always be free
