### ISSUE TITLE
Weekday Overlap on Weather Icon

### ISSUE THREAD

**Issue by PranshulGG** [Akylas/oss-weather#290]
In some locations, the weekdays overlap with the weather icons, as shown in the attached image

![Screenshot_20241230-133950.png](https://github.com/user-attachments/assets/e3986782-0876-46e8-9b7a-8d20bb77bcbe)

**Comment by farfromrefug** [comment]
@PranshulGG this should not happen.
Whats your phone / android version?
What the system font scale? is it 1?
Your phone and the app are in english?

**Comment by PranshulGG** [comment]
> @PranshulGG this should not happen. Whats your phone / android version? What the system font scale? is it 1? Your phone and the app are in english?

Device: Infinix Note 40 Pro
Android version: 14
Font scale: 1 (default)
Language: English

**Comment by farfromrefug** [comment]
@PranshulGG thanks! and it happens only for some locations? if so can you share one where it happens?

**Comment by PranshulGG** [comment]
> @PranshulGG thanks! and it happens only for some locations? if so can you share one where it happens?

I found that when you change the font scale and then press reset or set it back to 1, it doesn’t change. However, it gets fixed after a restart, so I’ll close this.
