### ISSUE TITLE
Use 24 hour time with english language is not available

### ISSUE THREAD

**Issue by badener95** [Akylas/oss-weather#32]
If the app language is set to auto or English the time is always displayed in am/pm. Because my language (German) is not available yet, I would like to keep using the app in English but with 24 hour time. I believe this was possible in the past, but I can't remember with version of the app has changed that.

**Comment by farfromrefug** [comment]
@badener95 great idea will add the option

**Comment by farfromrefug** [comment]
@badener95 BTW if you translate that file values to German and share it with me I can easily add support for it
https://github.com/Akylas/oss-weather/blob/master/app/i18n/en.json

**Comment by badener95** [comment]
Thanks for the quick implementation! I will translate the strings as soon as I find some time to do it.

**Comment by farfromrefug** [comment]
@badener95 I forgot to tells you. Normally you don't need to use the 24 hour format option in the app. By default the app use the value of the system 24 hour format option. Have you that turned on?

**Comment by badener95** [comment]
My device is set to 24 hour format, but that did not work for me. Only when the app language was manually switched to Spanish or French the time was shown in 24 hour format, but then I can't understand the forecast.
My device is a Google Pixel 4a with android 13.

**Comment by farfromrefug** [comment]
@badener95 OK that s a bug then ! Will try to fix that
