### ISSUE TITLE
Problems with deploy

### ISSUE THREAD

**Issue by Johnnywick1** [Akylas/oss-weather#40]
Hello,

Is it any instruction how to deploy it? Can I deploy it on services like Netlify, Vercel, etc.? Could you write an instruction steb by step how to deploy this repo? If it is open spurce repo so should be some install instruction.

When I install I have these errors:

"--> npm install @nativescript-community/observable @nativescript-community/ui-material-core \~ webpack
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: @nativescript/core@8.5.2
npm ERR! node_modules/@nativescript/core
npm ERR!   dev @nativescript/core@"8.5.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @nativescript/core@"~8.1.3" from svelte-native@1.0.6
 sh -c ./.config/build.sh
▲ [WARNING] Duplicate key "release" in object literal [duplicate-object-key]

    app.webpack.config.js:600:20:
      600 │                     release: `${nconfig.id}@${appVersi...
          ╵                     ~~~~~~~

  The original key "release" is here:

    app.webpack.config.js:597:20:
      597 │                     release: appVersion,
          ╵                     ~~~~~~~

 node --enable-source-maps .build/index.js
node:internal/modules/cjs/loader:988
  throw err;
  ^

Error: Cannot find module '/home/runner/oss-weather-2/.build/index.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.Module._load (node:internal/modules/cjs/loader:833:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
exit status 1"

What do I do wrong?

Thank you

**Comment by farfromrefug** [comment]
@Johnnywick1 what are you trying to do? This is an android/iOS app. Why are you talking about netlify or vercel?

**Comment by Johnnywick1** [comment]
Sorry, I'm new at this.

**Comment by Johnnywick1** [comment]
Yes. you can delete or close this message. Thank you
