### ISSUE TITLE
Can't select favourites

### ISSUE THREAD

**Issue by herm2222** [Akylas/oss-weather#41]
Hello,

when I set a city as a favourite with a star, I should be able to select that city in the sidebar. 

But when I click on a set favourite in the sidepanel, it does not change to that city in the main view.

The delete button for removing a set favourite from the sidepanel works as expected.

**Comment by farfromrefug** [comment]
@herm2222 strange it works here. What your phone and android version ?

**Comment by Paul75** [comment]
It same for me.

But if I persevere and try to click everywhere on the favorite in the long run it works but it's random.

**Comment by farfromrefug** [comment]
@Paul75 @herm2222 I think it is a sensitivity issue. Could you confirm that it is hard but sometimes you get it ?

**Comment by Paul75** [comment]
Yes I confirm it. it seams like the event of click is not correctly done on the item ....

**Comment by Paul75** [comment]
Hello,

I found the solution : If I click on left of the line it works.....

**Comment by farfromrefug** [comment]
@Paul75 i just published a new version which should make it much better. Let me know when you can test it

**Comment by Paul75** [comment]
Hello,

I test and now works !

**Comment by MattRGX** [comment]
> @Paul75 i just published a new version which should make it much better. Let me know when you can test it

When will it be available on f-droid ?

**Comment by farfromrefug** [comment]
Would say tomorrow

**Comment by ChrisRenfrow** [comment]
I can confirm that I had this issue, but as of 1.6.1.69 I can now select favorites.
