### ISSUE TITLE
Location Names

### ISSUE THREAD

**Issue by brokenbadger** [Akylas/oss-weather#43]
Hi,

Would it be possible to make it so that you could rename favorites, instead of just showing a GPS coordinate please?

**Comment by brokenbadger** [comment]
Or even better, a way of location names being detected from GPS coordinate s automatically.

**Comment by farfromrefug** [comment]
@brokenbadger it is already using geocoding to try and find location name. Will have to look at why it would not work. 
And good idea about renaming favorites!

**Comment by brokenbadger** [comment]
Sorry, just looking at it again, it looks as though I can search for my location by name its just that it doesn't associate my GPS coordinates with that name.
That's no problem.
Would really appreciate the renaming feature though if possible?
I have found one other issue, but I'll raise as a separate ticket for consistency.
Thanks for the prompt reply.

**Comment by farfromrefug** [comment]
@brokenbadger i just tried and and geocoding works correctly here when i search for my gps position.
What s your phone? android os and version?

**Comment by brokenbadger** [comment]
My phone is a Pixel 7, OS is GraphineOS and version is Android 13.
I'm just wondering if I'm just an edge case? Technically I'm  on the edge of a city, so maybe I just fall outside according to the geocoding? If thats the case then being able to rename favorites would be a more than acceptable solution?

**Comment by farfromrefug** [comment]
@brokenbadger might be due to your ROM. You are not using microg or gapps? Without them you won't have geocoding

**Comment by brokenbadger** [comment]
Ah OK, that'd make sense.
Thanks for looking into it anyway


-- 
 Securely sent with Tutanota.


10 Jun 2023, 22:50 by ***@***.***:
