### ISSUE TITLE
Air Quality

### ISSUE THREAD

**Issue by RageGamerBoi** [Akylas/oss-weather#44]
Air quality is starting to feel like a very important metric for anyone in the US right now...

![64822439a460da0019242040](https://github.com/Akylas/oss-weather/assets/105567407/9fa487cc-7de3-4ee2-b326-8f17fb4e1170)
(it's not that bad where I am, and the worst is over, but it's still there)

It would be very nice to have it in the app to check, similar to the UV index metric.
Thanks :)

**Comment by Saijin-Naib** [comment]
Yeah, this would be invaluable

**Comment by farfromrefug** [comment]
yes I plan on adding it. open météo has an api for this.
the question is also how to integrate this ux wise.
any idea is welcome.

**Comment by Saijin-Naib** [comment]
The US EPA AirNow app handles it like this. 

![Screenshot_20240229-161506_AirNow](https://github.com/Akylas/oss-weather/assets/19295950/7fec1c79-d543-494e-9abf-b257d98e78c3)

![image5](https://github.com/Akylas/oss-weather/assets/19295950/6c8a4c2f-6de6-47f0-8370-dc106e290efe)

**Comment by farfromrefug** [comment]
@Saijin-Naib nice. But in this app we need a clean way to add it within the current UX. The thing is how do you add more and more data (pressure, air quality...) without cluttering and within the available space

**Comment by azertylr** [comment]
Yes it would be nice, as open-meteo API can provide this information!
Maybe as a new page, to avoid adding too much data on the main page?

**Comment by farfromrefug** [comment]
@azertylr @Saijin-Naib @RageGamerBoi is that design ok with you?
![Screenshot_1712932892](https://github.com/Akylas/oss-weather/assets/655344/25fe1309-2694-4d11-adc7-7d38ef188fb3)

**Comment by RageGamerBoi** [comment]
Looks good but feels out of place.
Like it's too big or something (especially in the weekly view).
Maybe separate the number and treat "aqi" like the km/h under the wind icon.
The icon could be something like this <https://duckduckgo.com/?q=fog+icon&t=fpas&iax=images&ia=images&iai=https%3A%2F%2Fclipartmag.com%2Fimages%2Ffog-png-14.png>

**Comment by RageGamerBoi** [comment]
Looks good but feels out of place.
Like it's too big or something (especially in the weekly view).
I think it should at least be scaled down.

You could also separate the number and treat "aqi" like the km/h under the wind icon, then just use a normal icon like all of the other things.

Also is it possible for there be some kind of info panel when tapped, providing more details similar to Breezy Weather?
![image](https://github.com/Akylas/oss-weather/assets/105567407/67ce875a-2603-46cb-b299-b20a5c5ac3c9)

**Comment by farfromrefug** [comment]
@RageGamerBoi thanks foe the insight! Will test further. Might also test a new design based on an icon like other weather data

**Comment by farfromrefug** [comment]
@RageGamerBoi here is another design:
![Screenshot_1712950420](https://github.com/Akylas/oss-weather/assets/655344/72f10f3f-a531-47c7-baab-e874cc76c252)

**Comment by RageGamerBoi** [comment]
I like that.
The leaf could be rotated a little bit counter-clockwise, but otherwise it's good 👍

**Comment by azertylr** [comment]
it looks very nice! Great job :) I would write AQI in upper case.
Is it possible to have the details of the air quality index if we click on the leaf?

**Comment by farfromrefug** [comment]
@azertylr tried aqi in uppercase but it looked weird compared to "other" infos. Will try again.
As details yes i ll add it in the future. But not in the first iteration.

**Comment by farfromrefug** [comment]
@azertylr @Saijin-Naib @RageGamerBoi new version out with basic AQI support. Will add more in the future

**Comment by farfromrefug** [comment]
@azertylr @Saijin-Naib @RageGamerBoi i have added pollutants and pollens on daily view. I will close this now.
Still one thing i would want is alternative sources
