### ISSUE TITLE
Can't scroll on favorite side bar.

### ISSUE THREAD

**Issue by MattRGX** [Akylas/oss-weather#45]
Hello,
I've added more than 10 favorites and on my side bar i can't scroll down the list to see those above 10th rank. I can only see the first ten favorites.

I think you could maybe add the possibility to scroll down the favorites list.

Thanks

**Comment by farfromrefug** [comment]
@MattRGX thanks never tried that many :) will fix as soon as possible

**Comment by ChrisRenfrow** [comment]
Confirmed as implemented in 1.6.2.70

**Comment by MattRGX** [comment]
Yes i confirm that it is implemented.

Thanks
