### ISSUE TITLE
Current temperature doesn't update when switching locations

### ISSUE THREAD

**Issue by ChrisRenfrow** [Akylas/oss-weather#46]
Selecting one location and switching to another doesn't update to the expected current temperature or the high/low temperature for the new location.

<img src="https://github.com/Akylas/oss-weather/assets/2700549/59b32d1e-3210-4bc2-924a-7cdf0fc11efc" width="50%" />
<img src="https://github.com/Akylas/oss-weather/assets/2700549/d77b7b68-c2d3-41f4-a1b4-e48ba0cf8af0" width="50%" />

**Comment by farfromrefug** [comment]
@ChrisRenfrow thanks already fixed locally

**Comment by ChrisRenfrow** [comment]
Confirmed that this is fixed as of 670e689326ccf14c27a8a7787a250904a9ea47d1
