### ISSUE TITLE
Show local time, rather than "current location" time

### ISSUE THREAD

**Issue by sconim** [Akylas/oss-weather#51]
Display local time, instead of the time at "Current Location" when showing a location with a different local time. For example, if I'm in NY and I'd like to see the weather in LA, the time shown on the origin of time axis should be 3:00 hours behind New York.
Currently, the time for all locations is shown in reference to the Current Location, rather than local time.

**Comment by sconim** [comment]
Still unaddressed in the version updated today.

**Comment by farfromrefug** [comment]
@sconim indeed and i am not sure when i will be able to add it. I dont have access to the time zone of the current location right now. And storing the data in app would be really big,  i dont want to add it locally

**Comment by sconim** [comment]
> @sconim indeed and i am not sure when i will be able to add it. I dont have access to the time zone of the current location right now. And storing the data in app would be really big, i dont want to add it locally

As I see it, you don't need access to the time zone of current location, but to the time zones of saved favorites, which is easier to get. The current location should use the time zone of the device itself, while the favorites should use the time zone of their own location in the world. I hope this clarifies my point, and makes it easier to implement. 

Thank you for your effort, the app has great potential.

**Comment by farfromrefug** [comment]
When I say current location I mean also saved favorites. I need to use a web API to get the timezone which I dont really like

**Comment by farfromrefug** [comment]
@sconim it is now implemented in latest version
