### ISSUE TITLE
Wind gust colour and dark theme

### ISSUE THREAD

**Issue by Wintandre** [Akylas/oss-weather#54]
It's great that you are now including the wind gust speeds. However the current colour of red text on a dark background is quite difficult to read. Perhaps some shade of yellow could be used instead? It would be legible and stand out from the normal wind speed shown in white.

Also, strong gusty wind can be damaging to property, so anything over (for example) 80km/h | 50mph could be shown as white text on a red background tile to make it stand out.

Using v1.7.0.73 on Android 13

**Comment by farfromrefug** [comment]
@Wintandre i tried to improve in latest version (1.7.1). Let me know what you think
