### ISSUE TITLE
Météo France error when searching for a city not in France.

### ISSUE THREAD

**Issue by MattRGX** [Akylas/oss-weather#58]
Hello,

When searching for a city outside of France (tried with Coppenhagen and Tokyo) with Meteo-France set as provider, it gives an error : 

"Cannot read properties of undefined (reading gridded)"

Works fine with cities in France.

I'm on Android 13 with latest (1.7.1.74)

Thanks

**Comment by farfromrefug** [comment]
@MattRGX thanks i cant reproduce the issue but i will still try to avoid it

**Comment by MattRGX** [comment]
> @MattRGX thanks i cant reproduce the issue but i will still try to avoid it

Do you want a screenshot ?

**Comment by farfromrefug** [comment]
@MattRGX not needed thanks I think I know where it happens. 
BTW what s your phone language ?
