### ISSUE TITLE
Cannot read properties of null (reading slice) 

### ISSUE THREAD

**Issue by topcaser** [Akylas/oss-weather#64]
Hi, I get this failure message right after opening the app (with my manual set location). The app is not usable any more for me.

**Comment by farfromrefug** [comment]
@topcaser sorry for the trouble. So to be clear:
* you installed the app
* you launched it and it worked
* you searched for a location and added it
* you restarted the app
* it crashes with that error?

Can you tell me what location you choosed? Did you change any app setting?

**Comment by topcaser** [comment]
Hi I got it running again by clearing cash and storage and setup all settings newly (incl API key). Don't know what caused the problem.
