### ISSUE TITLE
Weather map not showing any data

### ISSUE THREAD

**Issue by Jeosas** [Akylas/oss-weather#65]
Hi,

First of, thanks for the great app, it does all I need, in simple concise way. Loving it.

I was looking into the weather map section which from what I understand from the sceenshots should show precipitation data. It would be so helpful to forcast rain when on a biking roadtrip!

Unfortunatly I only see the osm layer and not the precipitation data one.

Is it just me ? Or is it a known issue ?( could find anything related to this in the existing GH issues)

From what I saw in the code in `map/index.ts`, at the very bottom, it seems that the url used to call OW's map API could be wrong since it seems different from the [documentation](https://openweathermap.org/api/weather-map-2).

Note that I use a personal OW api key, I might have missed something when setting it up.

Thanks for your inputs !

**Comment by farfromrefug** [comment]
@Jeosas Very good catch. Sadly the weather map data is only available with an OpenWeatherMap api key ...
It is now disabled if you dont have one.
Sorry

**Comment by Jeosas** [comment]
Hmm I have a personal OWM "One call API" key though, isn't it what is needed for this feature ?

Do you mind if I look into it ? (updating the api url to [Global precipitation api](https://openweathermap.org/api/global-precipitation-map) and limiting the feature to OWM key owners)

**Comment by farfromrefug** [comment]
@Jeosas sûre you can look into it. But yes if you have a key it should work. The easiy test is to make a request like in my app with your API key. See what is return: an image or an error.

**Comment by Jeosas** [comment]
Indeed, I'll test this out 👌

**Comment by Jeosas** [comment]
Alright, I checked the API call with my own key, and I get a 401 on the map request.. so this seems to be the problem.

I tested my API key on a onecall forecast request and it works as expected.

Is there an option I'm missing in my free OWM subscription ? Do you manage to have precipitation maps info with a free API key ?

**Comment by Jeosas** [comment]
After further reading and investigation, seems that your current 'map/indes.ts' component already uses the "Weather maps 2.0" api (from my understanding).
Sadly this map 2.0 API is only available to OWM paid tier subscription. Free accounts are limited to the maps 1.0 API.

Farewell weather map 😢

**Comment by Jeosas** [comment]
In the end, it's the same issue that #57
Sorry for duplicate

I'll keep this open for now, I plan to lookaround to fix things up

**Comment by farfromrefug** [comment]
OK  weird though all keys would work with map data

**Comment by farfromrefug** [comment]
@s38b35M5 yes this is why there was none. But now the app has switched api for the weather radar, it works without an api key!
