### ISSUE TITLE
OpenWeatherMap API error & crashing

### ISSUE THREAD

**Issue by exstntlmsnthrp** [Akylas/oss-weather#66]
Hello. I've been using the app for quite awhile now but have recently been having some problems. 

It feels like these problems started happening around version 1.7.1. I use OpenWeatherMap for this app and several others and have my own private API key. When I initially open the app I get a pop-up asking me for my key, which is already there. 

![Ossweather.png](https://github.com/Akylas/oss-weather/assets/57594290/e65d5607-cdcf-4899-b58b-a506a432c73e)

When I click save, the app will crash every time and I have to manually clear it from active apps or it will crash when I try to open it again. If I do not touch save, but touch the screen anywhere else, the pop-up will disappear; however, the app will not automatically update. I have to select the ellipsis and touch refresh. If I pull down to refresh, about half of the time nothing happens. The other half of the time, the app will crash. 

I couldn't find anywhere to collect logs for you. If there is, please let me know. 

OS: Android 14 - GrapheneOS
Device: Pixel 7 pro
App version: 1.7.5.77
APK source: GitHub

**Comment by farfromrefug** [comment]
@exstntlmsnthrp I LL take a look at it thanks for reporting

**Comment by exstntlmsnthrp** [comment]
@farfromrefug Brilliant! I downloaded as soon as I saw it available and I don't have any problems now. And it remembers my API key. 

Did you refactor the build or something? It looks better! Thanks. 

The weather alerts are now working again too.

Cheers.

**Comment by farfromrefug** [comment]
@exstntlmsnthrp thanks. Yes i changed a lot for things! BTW you should look at the Open-Meteo provider. It is a free forever provider which is getting real good!
