### ISSUE TITLE
app won't start

### ISSUE THREAD

**Issue by AlphaElwedritsch** [Akylas/oss-weather#76]
Hi there
v1.8.4 Build 85 won't start on my iodéOS (Android 13). Keeps crashing after splash screen
v1.8.4 Build 84 works well

**Comment by mondlicht-und-sterne** [comment]
Hi there
v1.8.4 Build 85 won't start on my Samsung S21 5G (Android 14). Keeps crashing after splash screen
v1.8.4 Build 84 works well

**Comment by farfromrefug** [comment]
sorry about that . will be fixed in a few hours top

**Comment by farfromrefug** [comment]
@mondlicht-und-sterne @AlphaElwedritsch There is a new version up on github. I am publishing now on the play store.
Sorry for the trouble...

**Comment by AlphaElwedritsch** [comment]
@farfromrefug 
No reason to apologize. Errors can always occur with software. That's why you report it and it gets fixed. :wink: 
The new version works perfectly again. :+1: 
Thank you

**Comment by AlphaElwedritsch** [comment]
A quick question that has nothing directly to do with the topic, but I'll allow it anyway.

Which weather provider is more recommended, better and more accurate for weather in Germany?
Openmeteo or Openweathermap?

**Comment by farfromrefug** [comment]
@AlphaElwedritsch My first thought would say Open-Meteo. However it is not always true. For example here in France even if Open-Meteo uses MeteoFrance data, i always feel like Meteo-France provider gives better result.
I mean that Open-Meteo is great but not perfect yet and might vary depending on the location.

I would say compare them a bit (i need to find a way to make it fast and easy to switch provider, maybe even compare them). Take a few days to look which one is closer to the reality.
Sorry it is not a perfect answer but with weather prediction it is hard to get a perfect one :P

**Comment by AlphaElwedritsch** [comment]
Thanks
That was exactly my thoughts too

**Comment by mondlicht-und-sterne** [comment]
Open-Meteo

**Comment by AlphaElwedritsch** [comment]
yes, i've tested it the last three days, and yes, OpenMeteo is more accurate
