### ISSUE TITLE
Partial translations // German

### ISSUE THREAD

**Issue by AlphaElwedritsch** [Akylas/oss-weather#77]
When using OpenWeatherMap The DWD warning messages are only partially translated.
See the screenshot

![Screenshot_20240118-114105_OSS Wetter](https://github.com/Akylas/oss-weather/assets/109347938/391a4dd1-8d0d-49c0-ad39-a3f10ccf0a26)

**Comment by farfromrefug** [comment]
@AlphaElwedritsch i think it is an issue in OWM. THey must not translate that part. Same thing happens with Meteo-France. That text is not translated either.
Will try to check still
