### ISSUE TITLE
graphical glitches

### ISSUE THREAD

**Issue by AlphaElwedritsch** [Akylas/oss-weather#78]
When using Openweathermap

First Screenshot:
When starting the app initially. Everthing's fine

Second Screenshot:
When bringing the app in background and then in foreground again. The screen is shifted too far to the left

![Screenshot_20240118-114917_OSS Wetter_1](https://github.com/Akylas/oss-weather/assets/109347938/83947c18-d524-46b6-8f13-f7771423f6f0)

![Screenshot_20240118-114845_OSS Wetter_1](https://github.com/Akylas/oss-weather/assets/109347938/ac0f9308-f332-46ac-9520-6990826c6836)

**Comment by farfromrefug** [comment]
@AlphaElwedritsch it is fixed in latest
