### ISSUE TITLE
Explanation of used Picons/Symbols

### ISSUE THREAD

**Issue by AlphaElwedritsch** [Akylas/oss-weather#80]
Hi there,
is there a overview to see an explanation of all used weather picons/symbols/icons?

The most I#m interested in is this:

![image](https://github.com/Akylas/oss-weather/assets/109347938/2751b224-23a7-4edf-8db6-b7a074b74365)

**Comment by farfromrefug** [comment]
@AlphaElwedritsch no there is not :D Sorry. This one is for the uv index. Might have to find a better one

**Comment by AlphaElwedritsch** [comment]
Thanks
I thought it stood for the UV index
