### ISSUE TITLE
Second letter of Languages

### ISSUE THREAD

**Issue by symbuzzer** [Akylas/oss-weather#81]
![photo1706002191](https://github.com/Akylas/oss-weather/assets/9841184/f1c8ee0e-49f9-42f5-be94-0615073b5599)

Probably it is caused by "İ" charachter which is Turkish-specific

**Comment by farfromrefug** [comment]
@symbuzzer strange. Not sure what i can do about this :s

**Comment by symbuzzer** [comment]
> @symbuzzer strange. Not sure what i can do about this :s

It also exists document scanner app too

**Comment by symbuzzer** [comment]
> @symbuzzer Yes it will happen in all my apps. I use native android api to get localized name for each locale. I am now thinking it could be an issue with the "titlecase" algorithm i am using. Will try to run some tests

Thanks, waiting sir.

**Comment by farfromrefug** [comment]
@symbuzzer fixed in latest version

**Comment by symbuzzer** [comment]
@farfromrefug Can u fix this issue for scanner app too? I want to start translate it, thanks

**Comment by farfromrefug** [comment]
@symbuzzer yes it is already fixed, just not released. You can start translating

**Comment by symbuzzer** [comment]
> @symbuzzer yes it is already fixed, just not released. You can start translating

Done!
