### ISSUE TITLE
Units mismatch

### ISSUE THREAD

**Issue by s38b35M5** [Akylas/oss-weather#85]
Despite selecting imperial units, it seems only the hourly forecast respects that setting as far as wind speed is concerned. See below for examples.

![Screenshot_20240205-081125_OSS Weather_1](https://github.com/Akylas/oss-weather/assets/138058715/a51b998b-43ad-4ebc-923b-c31d0fdf222e)

![Screenshot_20240205-081104_OSS Weather_1](https://github.com/Akylas/oss-weather/assets/138058715/a52646fb-739e-41be-aa24-53b4c5853f6a)

**Comment by farfromrefug** [comment]
@s38b35M5 thanks for the report. will fix as soon as possible!

**Comment by farfromrefug** [comment]
@s38b35M5 should be fixed in latest

**Comment by s38b35M5** [comment]
Great improvement; thanks for the diligent work
