### ISSUE TITLE
Question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [Akylas/oss-weather#86]
Now that all new features of my APK scanner are active (see #72) and the next update of your nice weather app comes in, it finds something to complain about again:

```
! repo/com.akylas.weather_87.apk declares sensitive permission(s):
 android.permission.READ_EXTERNAL_STORAGE android.permission.ACCESS_COARSE_LOCATION
 android.permission.ACCESS_FINE_LOCATION android.permission.READ_PHONE_STATE
```

So once more I need your help for clarification :pray:

Let me check what I can find from your code, not being an Android dev myself I can at least read changelogs :see_no_evil:

* location, `versionCode: 70`: "update current weather data on location change" √
* storage: here I only see the declaration in `AndroidManifest.xml` and granting them in [`BaselineProfileGenerator.kt`](https://github.com/Akylas/oss-weather/blob/45dc60807a9ce554cfe1d37153c6b977ca5ecafa/App_Resources/Android/baselineprofile/src/main/java/com/example/baselineprofile/BaselineProfileGenerator.kt#L51), but not where they are used
* `READ_PHONE_STATE` I have no clue.

So may I ask your help for clarification once more?

![image](https://github.com/Akylas/oss-weather/assets/6781438/ef7cb3ba-3dfa-4d96-b045-7ac49a9a65cd)

As for `DEPENDENCY_INFO_BLOCK`, that's rather easy when you use gradle (no idea what you use for signing here):

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

**Comment by IzzySoft** [comment]
Ah, good: looks like `READ_PHONE_STATE` is gone now. So is the `DEPENDENCY_INFO_BLOCK`, cool! :star_struck: So only the storage one is left. Can you tell me what is saved to/read from "external storage"?

**Comment by farfromrefug** [comment]
@IzzySoft i use it to import/export app settings.  And thanks again for your amazing support!

**Comment by IzzySoft** [comment]
> to import/export app settings

thanks, added to the "green list" with that explanation then. For future versions you might consider switching to SAF (Storage Access Framework), which is available since Android 5 (corresponding to your `minSdkVer`). To export/import a single file this should be fully sufficient and you's no longer need the storage permissions. Instead folks using your app and wanting to export/import settings would be asked to pick a location they wish to grant your app access to.

> thanks again for your amazing support!

:heart_eyes: gladly given, thanks!

**Comment by IzzySoft** [comment]
Afraid the Droid-ify question you'll have to ask the Droid-ify devs, I cannot tell or change that.

As for multiple ABIs / split APKs, no plans yet. And I don't think I'll address that in the near future: 2 per-ABI APKs will even exceed the size of the "fat build", so at the current stage that doesn't make much sense. Not saying "never", though – but I wouldn't expect it this year.

**Comment by farfromrefug** [comment]
@IzzySoft you are right why did i asked you about the build number and how it appears in droid-ify :s my bad must have been too tired ...

I understand about the multiple / splits APK. You are right it would in many cases induce much bigger per release assets.
Had to ask, now i can answer my users. I will turn back on my personal repo for those users.
Thanks!

**Comment by IzzySoft** [comment]
Sure, and no prob! We're not in stasis, so things might change. Maybe next year, I cannot tell yet. Schedule is already well-filled with good things to come, stay tuned!
