### ISSUE TITLE
app won't start again

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [Akylas/oss-weather#87]
v1.8.7.88 won't start on my Samsung S21 5G (Android 14). Keeps crashing after splash screen

**Comment by mondlicht-und-sterne** [comment]
Now it works, funny. I'll close it then.

**Comment by farfromrefug** [comment]
@mondlicht-und-sterne that s weird their must be bug somewhere though! did you make anything to have it start again?

**Comment by mondlicht-und-sterne** [comment]
@farfromrefug 

No, but at first it really didn't work and then it did again. Curious.

**Comment by farfromrefug** [comment]
@mondlicht-und-sterne ok might be à crash related to weather data. may I ask what location you use in the app ? and what s your language

**Comment by mondlicht-und-sterne** [comment]
Location ? An city in Germany.

German.

**Comment by farfromrefug** [comment]
Ok will see if I can reproduce it
