### ISSUE TITLE
CM for snow instead of MM

### ISSUE THREAD

**Issue by 0-5-0** [Akylas/oss-weather#90]
Would it be possible to display CM for snow instead of MM? Millimeters work great for rain but it seems snow is better represented in centimeters if this data is available from the providers.

**Comment by farfromrefug** [comment]
@0-5-0 great idea. Not much snow this days so never really saw that :P will try to find a place to test it with

**Comment by 0-5-0** [comment]
Thank you :), I searched a bit for snowy place and found these:

Aomori (JP), Sapporo (JP), Toyama (JP), St. John's Newfoundland (CA), also St. Moritz (CH).

Some have rain coming but hopefully the timing is just right when you have a chance to look at it :P

**Comment by farfromrefug** [comment]
@0-5-0 it is now fixed in the new version on github

**Comment by 0-5-0** [comment]
I noticed using St. John's New Foundland as a test, when it's mixed precipitation rain and snow on the same day there's only one icon showing up in the list at the bottom, not one for rain and a second for snow so I think it's adding the mm of rain + cm of snow strangely.

It's showing 19.3mm 100% with the snow icon for St. John's today but looking at the hourly there's a mix of both rain and snow. Not sure if a separate icon for rain and snow would have to be added down in the list?

**Comment by farfromrefug** [comment]
@0-5-0 yes i use only one data. I show the total precipitation (snow+rain). as for the icon it chooses snow if there is some.
Not sure i want to add 2 icons. Uses a lot of space and not add that much. You ll get the details in the hourly view

**Comment by 0-5-0** [comment]
Unless one mixed precipitation icon would do in that case?

**Comment by farfromrefug** [comment]
you mean having an icon representing precipitation and snow at the same time ?

**Comment by 0-5-0** [comment]
Exactly, for days where it's forecasting both rain and snow with a small snow flake and small rain drop maybe in the same icon.

**Comment by farfromrefug** [comment]
@0-5-0 ok that i can do. i ll see if i find the right icon

**Comment by 0-5-0** [comment]
I tried to find "something" icon wise but it seems slim.. just looking for an icon that might show a large snowflake with a large rain drop separated by / ... aside from that I think "sleet" might be a common term but it's always paired with a cloud so might not fit the design.

I found these interesting general icon sets.

https://basmilius.github.io/weather-icons/index-line.html
https://github.com/erikflowers/weather-icons

I was about to give up and found this one:

https://thenounproject.com/icon/snow-6498631/

![noun-snow-6498631](https://github.com/Akylas/oss-weather/assets/112411524/98b96ef5-ffcd-47cf-b62d-406ff088a657)
![noun-snow-6498631](https://github.com/Akylas/oss-weather/assets/112411524/41f35347-33da-4cc3-81d0-cfd36cac244a)

Other examples:
https://www.veryicon.com/icons/miscellaneous/hekr/icon-defrost.html
https://www.iconfinder.com/icons/3625575/defrosting_drop_freezing_ice_rain_snow_weather_icon
https://www.iconfinder.com/icons/1813448/blood_drop_drops_rain_snow_water_weather_icon

**Comment by farfromrefug** [comment]
@0-5-0 awesome ! really like the animated weather icons. Might try to add that to the app!
i actually created a new icon. Just need to implement it now
![wi-raindrop-snowflake](https://github.com/Akylas/oss-weather/assets/655344/deba3c9b-158e-4281-b474-d9682c2adc9c)

**Comment by 0-5-0** [comment]
The one you made looks perfect, simple and very clear :)
