### ISSUE TITLE
Suggestion to add OSS Weather to Open-Meteo's Who is Using section

### ISSUE THREAD

**Issue by 0-5-0** [Akylas/oss-weather#91]
Would it be possible to add OSS Weather on Open-Meteo's "Who is Using Open-Meteo" Readme page. I would be happy to create a pull request there if you can give me a blurb to add?

https://github.com/open-meteo/open-meteo
https://github.com/open-meteo/open-meteo/blob/main/README.md

Maybe:
OSS Weather (with a link to https://github.com/Akylas/oss-weather) - Multi-model/multi-provider Open Source Android Weather app

**Comment by farfromrefug** [comment]
@0-5-0 thanks a lot. Great idea. PR created https://github.com/open-meteo/open-meteo/pull/669

**Comment by 0-5-0** [comment]
Excellent :)

**Comment by 0-5-0** [comment]
Looks like the PR was merged, looks great.
