### ISSUE TITLE
Add location indicator dot to radar map

### ISSUE THREAD

**Issue by 0-5-0** [Akylas/oss-weather#94]
Suggestion to add a location indicator dot for the current location/weather location on the radar map, this would be useful when the entire map is full of "weather" to help pin point the original location, especially when moving or zooming the map around.

I'm not sure if Rainviewer would provide some type of transparency otherwise so we can see names or landmarks on the map?

Something like this for opacity/transparency:

![image](https://github.com/Akylas/oss-weather/assets/112411524/3341dc72-0399-4f15-8856-29fc0e63331b)

I think it might be in https://github.com/Akylas/oss-weather/blob/78adcf94274a8ff106530a7feb77f76a1daf1db8/map/index.ts, setting opacity to 0.5 or 0.7?

Referenced from (https://github.com/rainviewer/rainviewer-api-example/blob/master/rainviewer-api-example.html):

maxZoom: 18,
pmIgnore: false,
opacity=0.5

Example without opacity (you can also test out different colour themes):
https://rainviewer.github.io/rainviewer-api-example/rainviewer-api-example.html

Example with opacity (0.5) adjustable through the little icon in the bottom right:
https://mwasil.github.io/Leaflet.Rainviewer/demo/

**Comment by farfromrefug** [comment]
@0-5-0 it is released!

**Comment by 0-5-0** [comment]
Location indicator looks great, opacity looks great :), thanks again lol
