### ISSUE TITLE
Customization for number of days shown in the list

### ISSUE THREAD

**Issue by 0-5-0** [Akylas/oss-weather#95]
Suggestion to add customization for the number of days shown in the list, some weather models or providers only show wind, UV or precipitation numbers for 5 or 7 days as an example. 

At the same time since longer forecasts are less accurate I wouldn't mind being able to set the maximum number of days displayed in the list to 5 or 7 days instead of 12 days, allowing me to focus on just the ones I want to see without scrolling too far past them.

**Comment by farfromrefug** [comment]
@0-5-0 it is released!

**Comment by 0-5-0** [comment]
There's a typo in the text under settings, says "forcast" but should be "forecast", aside from that it says 16 days as the max but if I select it it gives me an error, if I choose 15 days it shows 14, choosing 14 days shows 13 and so on.

There might be a number off somewhere.

Trimming the list works great otherwise, just off by 1 number compared to what's selected in the settings.

**Comment by farfromrefug** [comment]
@0-5-0 the number takes the current day into account. so if you choose 5 it will show 4 days after today. could change that

**Comment by 0-5-0** [comment]
That makes sense if it includes the current day's forecast at the top. If someone might only want to show the current day's forecast and nothing else.

Not sure if writing the text as "Number of days to forecast (includes Current)" might clear things up.

Number of days 16 gives me a the following error "Forecast days is invalid. Allowed range 0 to 16. Given 16."

**Comment by farfromrefug** [comment]
@0-5-0 YOu are right will change the text. About 16 guess it was too much for OM. Will put 15 as max. BTW it depends on the provider, with OM i can ask up to 15. For other i can only filter from what the api returns (which can me much less).
BTW @0-5-0 I really want to thank you for your contributions. You can contact me by mail if you want.

**Comment by 0-5-0** [comment]
Yes I guess Meteo France goes up to 16, Open-Meteo is 15 and OpenWeatherMap is 8. 

Maybe the wording could be "Number of days to show if available (includes Current)", to kind of hint that it doesn't guarantee the number, similar to the feels like setting.

@farfromrefug 
I'm happy to contribute what I can, looking for Open-Meteo apps it was initially a bit hard to find but with key words in the description now and having it on the Open-Meteo page hopefully it'll bring more people who can also enjoy it. You've done so much work on this app and have been able to implement so many suggestions lately that I wanted to say thanks and why I became a supporter.

Exposing the Open-Meteo models I think you're the first to do that for Open-Meteo, transparency and colours on the map look great, CM vs MM again the first for Open-Meteo apps. Open-Meteo is a great API and accessing it from this app makes it even better :).

**Comment by 0-5-0** [comment]
Works fine with 15, "includes current" looks good.
