### ISSUE TITLE
Add colour choices for Rainviewer radar map

### ISSUE THREAD

**Issue by 0-5-0** [Akylas/oss-weather#96]
Suggestion to add colour choices for Rainviewer radar map.

You can test the different colours:
https://rainviewer.github.io/rainviewer-api-example/rainviewer-api-example.html

There's also a list of the different colours by searching for "setcolors":
https://github.com/rainviewer/rainviewer-api-example/blob/master/rainviewer-api-example.html

        <option value="0">Black and White Values</option>
        <option value="1">Original</option>
        <option value="2" selected="selected">Universal Blue</option>
        <option value="3">TITAN</option>
        <option value="4">The Weather Channel</option>
        <option value="5">Meteored</option>
        <option value="6">NEXRAD Level-III</option>
        <option value="7">RAINBOW @ SELEX-SI</option>
        <option value="8">Dark Sky</option>

**Comment by farfromrefug** [comment]
@0-5-0 thanks a lot for finding this.

**Comment by farfromrefug** [comment]
@0-5-0 it is released!

**Comment by 0-5-0** [comment]
Each colour is working great, thank you :)
